name: gdg_guess_game
description: A guess image game with multiple categories.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5
  win32: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/
    - assets/images/naruto/
    - assets/images/naruto/Orochimaru/
    - assets/images/naruto/Obito Uchiha/
    - assets/images/naruto/Naruto Uzumaki/
    - assets/images/naruto/Minato Namikaze/
    - assets/images/naruto/Might Guy/
    - assets/images/naruto/Madara Uchiha/
    - assets/images/naruto/Konohamaru Sarutobi/
    - assets/images/naruto/Kiba Inuzuka/
    - assets/images/naruto/Kakashi Hatake/
    - assets/images/naruto/Jiraiya/
    - assets/images/naruto/Itachi Uchiha/
    - assets/images/naruto/Hiruzen Sarutobi/
    - assets/images/naruto/Gaara/
    - assets/images/naruto/Tsunade/
    - assets/images/naruto/Shikamaru Nara/
    - assets/images/naruto/Sasuke Uchiha/
    - assets/images/naruto/Sakura Haruno/
    - assets/images/naruto/Rock Lee/
    - assets/images/vinland_saga/
    - assets/images/tokyo_revengers/
    - assets/images/solo_leveling/
    - assets/images/one_piece/
    - assets/images/my_hero_academia/
    - assets/images/jujutsu_kaisen/
    - assets/images/hunter_x_hunter/
    - assets/images/fmab/
    - assets/images/dragon_ball_z/
    - assets/images/dr_stone/
    - assets/images/detective_conan/
    - assets/images/demon_slayer/
    - assets/images/death_note/
    - assets/images/code_geass/
    - assets/images/bleach/
    - assets/images/0/
    - assets/images/black_clover/
    - assets/images/attack_on_titan/
    - assets/fonts/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-Italic.ttf
          style: italic
        - asset: assets/fonts/GoogleSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
