name: gdg_guess_game
description: A guess image game with multiple categories.
publish_to: 'none'

version: 1.0.0-beta.10+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.1
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  flutter_staggered_animations: ^1.1.1
  provider: ^6.1.5
  win32: ^5.0.0
  url_launcher: ^6.3.1
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/profile/
    - assets/fonts/
    - assets/images/
    - assets/images/0/
    - assets/images/attack_on_titan/
    - assets/images/attack_on_titan/Annie LEONHART/
    - assets/images/attack_on_titan/Armin ARLERT/
    - assets/images/attack_on_titan/Bertholdt HOOVER/
    - assets/images/attack_on_titan/Conny SPRINGER/
    - assets/images/attack_on_titan/Dot PYXIS/
    - assets/images/attack_on_titan/Eld GIN/
    - assets/images/attack_on_titan/Eren YAEGER/
    - assets/images/attack_on_titan/Erwin SMITH/
    - assets/images/attack_on_titan/Gunther SCHULTZ/
    - assets/images/attack_on_titan/Hannes/
    - assets/images/attack_on_titan/Hange ZOE/
    - assets/images/attack_on_titan/Jean KIRSCHTEIN/
    - assets/images/attack_on_titan/Levi ACKERMAN/
    - assets/images/attack_on_titan/Marco BODT/
    - assets/images/attack_on_titan/Mikasa ACKERMAN/
    - assets/images/black_clover/
    - assets/images/black_clover/Acier Silva/
    - assets/images/black_clover/Asta/
    - assets/images/black_clover/Augustus Kira Clover XIII/
    - assets/images/black_clover/Charlotte Roselei/
    - assets/images/black_clover/Charmy Pappitson/
    - assets/images/black_clover/Damnatio Kira/
    - assets/images/black_clover/Dante Zogratis/
    - assets/images/black_clover/Dorothy Unsworth/
    - assets/images/black_clover/Fana/
    - assets/images/black_clover/Finral Roulacase/
    - assets/images/black_clover/Fuegoleon Vermillion/
    - assets/images/black_clover/Gadjah/
    - assets/images/black_clover/Gauche Adlai/
    - assets/images/black_clover/Gifso/
    - assets/images/black_clover/Gordon Agrippa/
    - assets/images/black_clover/Grey/
    - assets/images/black_clover/Gueldre Poizot/
    - assets/images/black_clover/Henry Legolant/
    - assets/images/black_clover/Jack the Ripper/
    - assets/images/black_clover/Julius Novachrono/
    - assets/images/black_clover/Kahono/
    - assets/images/black_clover/Kaiser Granvorka/
    - assets/images/black_clover/Kiato/
    - assets/images/black_clover/Klaus Lunettes/
    - assets/images/black_clover/Langris Vaude/
    - assets/images/black_clover/Lemiel Silvamillion Clover/
    - assets/images/black_clover/Leopold Vermillion/
    - assets/images/black_clover/Liebe/
    - assets/images/black_clover/Lily Aquaria/
    - assets/images/black_clover/Lolopechka/
    - assets/images/black_clover/Luck Voltia/
    - assets/images/black_clover/Magna Swing/
    - assets/images/black_clover/Marie Adlai/
    - assets/images/black_clover/Mars/
    - assets/images/black_clover/Marx Francois/
    - assets/images/black_clover/Megicula/
    - assets/images/black_clover/Mereoleona Vermillion/
    - assets/images/black_clover/Mimosa Vermillion/
    - assets/images/black_clover/Nacht Faust/
    - assets/images/black_clover/Noelle Silva/
    - assets/images/black_clover/Nozel Silva/
    - assets/images/black_clover/Orsi Orfai/
    - assets/images/black_clover/Owen/
    - assets/images/black_clover/Patolli/
    - assets/images/black_clover/Rades Spirito/
    - assets/images/black_clover/Revchi Salik/
    - assets/images/black_clover/Rhya/
    - assets/images/black_clover/Richita/
    - assets/images/black_clover/Rill Boismortier/
    - assets/images/black_clover/Salamander/
    - assets/images/black_clover/Sally/
    - assets/images/black_clover/Secre Swallowtail/
    - assets/images/black_clover/Sekke Bronzazza/
    - assets/images/black_clover/Sol Marron/
    - assets/images/black_clover/Solid Silva/
    - assets/images/black_clover/Sylph/
    - assets/images/black_clover/Undine/
    - assets/images/black_clover/Vanessa Enoteca/
    - assets/images/black_clover/Vanica Zogratis/
    - assets/images/black_clover/Vetto/
    - assets/images/black_clover/William Vangeance/
    - assets/images/black_clover/Witch Queen/
    - assets/images/black_clover/Yami Sukehiro/
    - assets/images/black_clover/Yuno Grinberryall/
    - assets/images/black_clover/Zagred/
    - assets/images/black_clover/Zenon Zogratis/
    - assets/images/black_clover/Zora Ideale/
    - assets/images/demon_slayer/
    - assets/images/demon_slayer/Akaza/
    - assets/images/demon_slayer/Amane Ubuyashiki/
    - assets/images/demon_slayer/Daki/
    - assets/images/demon_slayer/Doma/
    - assets/images/demon_slayer/Enmu/
    - assets/images/demon_slayer/Genya Shinazugawa/
    - assets/images/demon_slayer/Giyu Tomioka/
    - assets/images/demon_slayer/Goto/
    - assets/images/demon_slayer/Gyokko/
    - assets/images/demon_slayer/Gyomei Himejima/
    - assets/images/demon_slayer/Gyutaro/
    - assets/images/demon_slayer/Hand Demon/
    - assets/images/demon_slayer/Hantengu/
    - assets/images/demon_slayer/Hotaru Haganezuka/
    - assets/images/demon_slayer/Inosuke Hashibira/
    - assets/images/demon_slayer/Kagaya Ubuyashiki/
    - assets/images/demon_slayer/Kanao Tsuyuri/
    - assets/images/demon_slayer/Kie Kamado/
    - assets/images/demon_slayer/Kiyo Terauchi and Sumi Nakahara and Naho Takada/
    - assets/images/demon_slayer/Kokushibo/
    - assets/images/demon_slayer/Kotetsu/
    - assets/images/demon_slayer/Kyogai/
    - assets/images/demon_slayer/Kyojuro Rengoku/
    - assets/images/demon_slayer/Mitsuri Kanroji/
    - assets/images/demon_slayer/Muichiro Tokito/
    - assets/images/demon_slayer/Muzan Kibutsuji/
    - assets/images/demon_slayer/Nakime/
    - assets/images/demon_slayer/Nezuko Kamado/
    - assets/images/demon_slayer/Obanai Iguro/
    - assets/images/demon_slayer/Rui/
    - assets/images/demon_slayer/Sabito/
    - assets/images/demon_slayer/Sakonji Urokodaki/
    - assets/images/demon_slayer/Sanemi Shinazugawa/
    - assets/images/demon_slayer/Shinobu Kocho/
    - assets/images/demon_slayer/Susamaru/
    - assets/images/demon_slayer/Tamayo/
    - assets/images/demon_slayer/Tanjiro Kamado/
    - assets/images/demon_slayer/Tanjuro Kamado/
    - assets/images/demon_slayer/Tecchin Tecchikawahara/
    - assets/images/demon_slayer/Tengen Uzui/
    - assets/images/demon_slayer/Yoriichi/
    - assets/images/demon_slayer/Yushiro/
    - assets/images/demon_slayer/Zenitsu Agatsuma/
    - assets/images/hunter_x_hunter/
    - assets/images/hunter_x_hunter/Abengane/
    - assets/images/hunter_x_hunter/Alluka Zoldyck/
    - assets/images/hunter_x_hunter/Amane/
    - assets/images/hunter_x_hunter/Anita/
    - assets/images/hunter_x_hunter/Baise/
    - assets/images/hunter_x_hunter/Bara/
    - assets/images/hunter_x_hunter/Basho/
    - assets/images/hunter_x_hunter/Beans/
    - assets/images/hunter_x_hunter/Binolt/
    - assets/images/hunter_x_hunter/Biscuit Krueger/
    - assets/images/hunter_x_hunter/Boki/
    - assets/images/hunter_x_hunter/Bonolenov Ndongo/
    - assets/images/hunter_x_hunter/Bopobo/
    - assets/images/hunter_x_hunter/Botobai Gigante/
    - assets/images/hunter_x_hunter/Bourbon/
    - assets/images/hunter_x_hunter/Buhara/
    - assets/images/hunter_x_hunter/Canary/
    - assets/images/hunter_x_hunter/Captain/
    - assets/images/hunter_x_hunter/Centipede/
    - assets/images/hunter_x_hunter/Cheadle Yorkshire/
    - assets/images/hunter_x_hunter/Cheetu/
    - assets/images/hunter_x_hunter/Chimera Ant Queen/
    - assets/images/hunter_x_hunter/Chrollo Lucilfer/
    - assets/images/hunter_x_hunter/Cluck/
    - assets/images/hunter_x_hunter/Cocco/
    - assets/images/hunter_x_hunter/Colt/
    - assets/images/hunter_x_hunter/Dalzollene/
    - assets/images/hunter_x_hunter/Dwun/
    - assets/images/hunter_x_hunter/Feitan Portor/
    - assets/images/hunter_x_hunter/Flutter/
    - assets/images/hunter_x_hunter/Franklin Bordeau/
    - assets/images/hunter_x_hunter/Gel/
    - assets/images/hunter_x_hunter/Genthru/
    - assets/images/hunter_x_hunter/Geretta/
    - assets/images/hunter_x_hunter/Gido/
    - assets/images/hunter_x_hunter/Ging Freecss/
    - assets/images/hunter_x_hunter/Ginta/
    - assets/images/hunter_x_hunter/Gon Freecss/
    - assets/images/hunter_x_hunter/Goreinu/
    - assets/images/hunter_x_hunter/Gotoh/
    - assets/images/hunter_x_hunter/Grachan/
    - assets/images/hunter_x_hunter/Gun-toting Ant/
    - assets/images/hunter_x_hunter/Gyro/
    - assets/images/hunter_x_hunter/Hanzo/
    - assets/images/hunter_x_hunter/Haruna/
    - assets/images/hunter_x_hunter/Heavens Arena/
    - assets/images/hunter_x_hunter/Hina/
    - assets/images/hunter_x_hunter/Hisoka Morow/
    - assets/images/hunter_x_hunter/Ikalgo/
    - assets/images/hunter_x_hunter/Illumi Zoldyck/
    - assets/images/hunter_x_hunter/Isaac Netero/
    - assets/images/hunter_x_hunter/Izunavi/
    - assets/images/hunter_x_hunter/Johness/
    - assets/images/hunter_x_hunter/Kaito the ant/
    - assets/images/hunter_x_hunter/Kalluto Zoldyck/
    - assets/images/hunter_x_hunter/Kanzai/
    - assets/images/hunter_x_hunter/Kastro/
    - assets/images/hunter_x_hunter/Kikyo Zoldyck/
    - assets/images/hunter_x_hunter/Killua Zoldyck/
    - assets/images/hunter_x_hunter/Kite/
    - assets/images/hunter_x_hunter/Knov/
    - assets/images/hunter_x_hunter/Knuckle Bine/
    - assets/images/hunter_x_hunter/Komugi/
    - assets/images/hunter_x_hunter/Kortopi/
    - assets/images/hunter_x_hunter/Kurapika/
    - assets/images/hunter_x_hunter/Kurt/
    - assets/images/hunter_x_hunter/Leech/
    - assets/images/hunter_x_hunter/Leol/
    - assets/images/hunter_x_hunter/Leorio Paradinight/
    - assets/images/hunter_x_hunter/Leroute/
    - assets/images/hunter_x_hunter/Light Nostrade/
    - assets/images/hunter_x_hunter/Lippo/
    - assets/images/hunter_x_hunter/List/
    - assets/images/hunter_x_hunter/Machi Komacine/
    - assets/images/hunter_x_hunter/Maha Zoldyck/
    - assets/images/hunter_x_hunter/Majtani/
    - assets/images/hunter_x_hunter/Meleoron/
    - assets/images/hunter_x_hunter/Melody/
    - assets/images/hunter_x_hunter/Menchi/
    - assets/images/hunter_x_hunter/Menthuthuyoupi/
    - assets/images/hunter_x_hunter/Meruem/
    - assets/images/hunter_x_hunter/Milluki Zoldyck/
    - assets/images/hunter_x_hunter/Mito Freecss/
    - assets/images/hunter_x_hunter/Mizaistom Nana/
    - assets/images/hunter_x_hunter/Morel Mackernasey/
    - assets/images/hunter_x_hunter/Mosquito/
    - assets/images/hunter_x_hunter/Neferpitou/
    - assets/images/hunter_x_hunter/Neon Nostrade/
    - assets/images/hunter_x_hunter/Nobunaga Hazama/
    - assets/images/hunter_x_hunter/Ortho/
    - assets/images/hunter_x_hunter/Owl/
    - assets/images/hunter_x_hunter/Pairo/
    - assets/images/hunter_x_hunter/Pakunoda/
    - assets/images/hunter_x_hunter/Palm Siberia/
    - assets/images/hunter_x_hunter/Pariston Hill/
    - assets/images/hunter_x_hunter/Phinks Magcub/
    - assets/images/hunter_x_hunter/Pike/
    - assets/images/hunter_x_hunter/Pokkle/
    - assets/images/hunter_x_hunter/Ponzu/
    - assets/images/hunter_x_hunter/Porcupine/
    - assets/images/hunter_x_hunter/Pyon/
    - assets/images/hunter_x_hunter/Quizzing Lady/
    - assets/images/hunter_x_hunter/Rabid Dog/
    - assets/images/hunter_x_hunter/Rammot/
    - assets/images/hunter_x_hunter/Razor/
    - assets/images/hunter_x_hunter/Reina/
    - assets/images/hunter_x_hunter/Riehlvelt/
    - assets/images/hunter_x_hunter/Saccho Kobayakawa/
    - assets/images/hunter_x_hunter/Sadaso/
    - assets/images/hunter_x_hunter/Saiyu/
    - assets/images/hunter_x_hunter/Satotz/
    - assets/images/hunter_x_hunter/Sedokan/
    - assets/images/hunter_x_hunter/Shachmono Tocino/
    - assets/images/hunter_x_hunter/Shaiapouf/
    - assets/images/hunter_x_hunter/Shalnark/
    - assets/images/hunter_x_hunter/Shidore/
    - assets/images/hunter_x_hunter/Shizuku Murasaki/
    - assets/images/hunter_x_hunter/Shoot McMahon/
    - assets/images/hunter_x_hunter/Silva Zoldyck/
    - assets/images/hunter_x_hunter/Squala/
    - assets/images/hunter_x_hunter/Tonpa/
    - assets/images/hunter_x_hunter/Tsezguerra/
    - assets/images/hunter_x_hunter/Tsubone/
    - assets/images/hunter_x_hunter/Uvogin/
    - assets/images/hunter_x_hunter/Welfin/
    - assets/images/hunter_x_hunter/Wing/
    - assets/images/hunter_x_hunter/Worm/
    - assets/images/hunter_x_hunter/Yunju/
    - assets/images/hunter_x_hunter/Zazan/
    - assets/images/hunter_x_hunter/Zeno Zoldyck/
    - assets/images/hunter_x_hunter/Zepile/
    - assets/images/hunter_x_hunter/Zigg Zoldyck/
    - assets/images/hunter_x_hunter/Zushi/
    - assets/images/hunter_x_hunter/eta and elena/
    - assets/images/hunter_x_hunter/sub/
    - assets/images/naruto/
    - assets/images/naruto/Akamaru/
    - assets/images/naruto/Choji Akimichi/
    - assets/images/naruto/Gaara/
    - assets/images/naruto/Hinata Hyuga/
    - assets/images/naruto/Hiruzen Sarutobi/
    - assets/images/naruto/Ino Yamanaka/
    - assets/images/naruto/Itachi Uchiha/
    - assets/images/naruto/Jiraiya/
    - assets/images/naruto/Kakashi Hatake/
    - assets/images/naruto/Kiba Inuzuka/
    - assets/images/naruto/Konohamaru Sarutobi/
    - assets/images/naruto/Madara Uchiha/
    - assets/images/naruto/Might Guy/
    - assets/images/naruto/Minato Namikaze/
    - assets/images/naruto/Naruto Uzumaki/
    - assets/images/naruto/Neji Hyuga/
    - assets/images/naruto/Obito Uchiha/
    - assets/images/naruto/Orochimaru/
    - assets/images/naruto/Rock Lee/
    - assets/images/naruto/Sakura Haruno/
    - assets/images/naruto/Sasuke Uchiha/
    - assets/images/naruto/Shikamaru Nara/
    - assets/images/naruto/Shizune/
    - assets/images/naruto/Tsunade/

  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/biguess-icon.webp"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/logos/biguess-icon.webp"
  windows:
    generate: true
    image_path: "assets/logos/biguess-icon.webp"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logos/biguess-icon.webp"