const Map<String, List<String>> categoryAssets = {
  'Attack on Titan': [
    // Annie LEONHART
    'assets/images/attack_on_titan/Annie LEONHART/image_1.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_2.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_3.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_4.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_5.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_6.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_7.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_8.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_9.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_10.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_11.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_12.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_13.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_14.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_15.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_16.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_17.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_18.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_19.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_20.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_21.webp',
    // Armin ARLERT
    'assets/images/attack_on_titan/Armin ARLERT/image_1.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_2.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_3.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_4.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_5.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_6.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_7.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_8.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_9.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_10.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_11.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_12.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_13.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_14.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_15.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_16.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_17.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_18.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_19.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_20.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_21.webp',
    // Bertholdt HOOVER
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_1.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_2.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_3.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_4.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_5.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_6.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_7.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_8.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_9.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_10.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_11.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_12.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_13.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_14.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_15.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_16.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_17.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_18.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_19.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_20.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_21.webp',
    // Conny SPRINGER
    'assets/images/attack_on_titan/Conny SPRINGER/image_1.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_2.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_3.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_4.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_5.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_6.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_7.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_8.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_9.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_10.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_11.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_12.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_13.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_14.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_15.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_16.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_17.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_18.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_19.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_20.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_21.webp',
    // Dot PYXIS
    'assets/images/attack_on_titan/Dot PYXIS/image_1.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_2.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_3.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_4.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_5.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_6.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_7.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_8.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_9.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_10.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_11.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_12.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_13.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_14.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_15.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_16.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_17.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_18.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_19.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_20.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_21.webp',
    // Eld GIN
    'assets/images/attack_on_titan/Eld GIN/image_1.webp',
    'assets/images/attack_on_titan/Eld GIN/image_2.webp',
    'assets/images/attack_on_titan/Eld GIN/image_3.webp',
    'assets/images/attack_on_titan/Eld GIN/image_4.webp',
    'assets/images/attack_on_titan/Eld GIN/image_5.webp',
    'assets/images/attack_on_titan/Eld GIN/image_6.webp',
    'assets/images/attack_on_titan/Eld GIN/image_7.webp',
    'assets/images/attack_on_titan/Eld GIN/image_8.webp',
    'assets/images/attack_on_titan/Eld GIN/image_9.webp',
    'assets/images/attack_on_titan/Eld GIN/image_10.webp',
    'assets/images/attack_on_titan/Eld GIN/image_11.webp',
    'assets/images/attack_on_titan/Eld GIN/image_12.webp',
    'assets/images/attack_on_titan/Eld GIN/image_13.webp',
    'assets/images/attack_on_titan/Eld GIN/image_14.webp',
    'assets/images/attack_on_titan/Eld GIN/image_15.webp',
    'assets/images/attack_on_titan/Eld GIN/image_16.webp',
    'assets/images/attack_on_titan/Eld GIN/image_17.webp',
    'assets/images/attack_on_titan/Eld GIN/image_18.webp',
    'assets/images/attack_on_titan/Eld GIN/image_19.webp',
    'assets/images/attack_on_titan/Eld GIN/image_20.webp',
    'assets/images/attack_on_titan/Eld GIN/image_21.webp',
    // Eren YAEGER
    'assets/images/attack_on_titan/Eren YAEGER/image_1.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_2.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_3.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_4.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_5.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_6.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_7.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_8.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_9.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_10.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_11.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_12.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_13.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_14.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_15.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_16.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_17.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_18.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_19.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_20.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_21.webp',
    // Erwin SMITH
    'assets/images/attack_on_titan/Erwin SMITH/image_1.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_2.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_3.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_4.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_5.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_6.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_7.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_8.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_9.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_10.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_11.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_12.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_13.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_14.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_15.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_16.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_17.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_18.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_19.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_20.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_21.webp',
    // Gunther SCHULTZ
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_1.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_2.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_3.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_4.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_5.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_6.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_7.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_8.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_9.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_10.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_11.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_12.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_13.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_14.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_15.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_16.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_17.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_18.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_19.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_20.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_21.webp',
    // Hange ZOE
    'assets/images/attack_on_titan/Hange ZOE/image_1.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_2.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_3.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_4.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_5.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_6.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_7.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_8.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_9.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_10.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_11.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_12.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_13.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_14.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_15.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_16.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_17.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_18.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_19.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_20.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_21.webp',
    // Hannes
    'assets/images/attack_on_titan/Hannes/image_1.webp',
    'assets/images/attack_on_titan/Hannes/image_2.webp',
    'assets/images/attack_on_titan/Hannes/image_3.webp',
    'assets/images/attack_on_titan/Hannes/image_4.webp',
    'assets/images/attack_on_titan/Hannes/image_5.webp',
    'assets/images/attack_on_titan/Hannes/image_6.webp',
    'assets/images/attack_on_titan/Hannes/image_7.webp',
    'assets/images/attack_on_titan/Hannes/image_8.webp',
    'assets/images/attack_on_titan/Hannes/image_9.webp',
    'assets/images/attack_on_titan/Hannes/image_10.webp',
    'assets/images/attack_on_titan/Hannes/image_11.webp',
    'assets/images/attack_on_titan/Hannes/image_12.webp',
    'assets/images/attack_on_titan/Hannes/image_13.webp',
    'assets/images/attack_on_titan/Hannes/image_14.webp',
    'assets/images/attack_on_titan/Hannes/image_15.webp',
    'assets/images/attack_on_titan/Hannes/image_16.webp',
    'assets/images/attack_on_titan/Hannes/image_17.webp',
    'assets/images/attack_on_titan/Hannes/image_18.webp',
    'assets/images/attack_on_titan/Hannes/image_19.webp',
    'assets/images/attack_on_titan/Hannes/image_20.webp',
    'assets/images/attack_on_titan/Hannes/image_21.webp',
    // Jean KIRSCHTEIN
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_1.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_2.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_3.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_4.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_5.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_6.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_7.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_8.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_9.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_10.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_11.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_12.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_13.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_14.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_15.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_16.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_17.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_18.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_19.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_20.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_21.webp',
    // Levi ACKERMAN
    'assets/images/attack_on_titan/Levi ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_5.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_6.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_7.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_8.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_9.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_10.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_11.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_12.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_13.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_14.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_15.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_16.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_17.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_18.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_19.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_20.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_21.webp',
    // Marco BODT
    'assets/images/attack_on_titan/Marco BODT/image_1.webp',
    'assets/images/attack_on_titan/Marco BODT/image_2.webp',
    'assets/images/attack_on_titan/Marco BODT/image_3.webp',
    'assets/images/attack_on_titan/Marco BODT/image_4.webp',
    'assets/images/attack_on_titan/Marco BODT/image_5.webp',
    'assets/images/attack_on_titan/Marco BODT/image_6.webp',
    'assets/images/attack_on_titan/Marco BODT/image_7.webp',
    'assets/images/attack_on_titan/Marco BODT/image_8.webp',
    'assets/images/attack_on_titan/Marco BODT/image_9.webp',
    'assets/images/attack_on_titan/Marco BODT/image_10.webp',
    // Mikasa ACKERMAN
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_5.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_6.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_7.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_8.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_9.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_10.webp',
  ],
  'Black Clover': [],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Demon Slayer': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
};