const Map<String, List<String>> categoryAssets = {
  'Naruto': [
    // Orochimaru
    'assets/images/naruto/Orochimaru/image_1.webp',
    'assets/images/naruto/Orochimaru/image_2.webp',
    'assets/images/naruto/Orochimaru/image_3.webp',
    'assets/images/naruto/Orochimaru/image_4.webp',
    'assets/images/naruto/Orochimaru/image_5.webp',
    'assets/images/naruto/Orochimaru/image_6.webp',
    // Obito Uchiha
    'assets/images/naruto/Obito Uchiha/image_1.webp',
    'assets/images/naruto/Obito Uchiha/image_2.webp',
    'assets/images/naruto/Obito Uchiha/image_3.webp',
    'assets/images/naruto/Obito Uchiha/image_4.webp',
    'assets/images/naruto/Obito Uchiha/image_5.webp',
    'assets/images/naruto/Obito Uchiha/image_6.webp',
    'assets/images/naruto/Obito Uchiha/image_7.webp',
    // Naruto Uzumaki
    'assets/images/naruto/Naruto Uzumaki/image_1.webp',
    'assets/images/naruto/Naruto Uzumaki/image_2.webp',
    'assets/images/naruto/Naruto Uzumaki/image_3.webp',
    'assets/images/naruto/Naruto Uzumaki/image_4.webp',
    'assets/images/naruto/Naruto Uzumaki/image_6.webp',
    // Minato Namikaze
    'assets/images/naruto/Minato Namikaze/image_1.webp',
    'assets/images/naruto/Minato Namikaze/image_2.webp',
    'assets/images/naruto/Minato Namikaze/image_3.webp',
    'assets/images/naruto/Minato Namikaze/image_4.webp',
    'assets/images/naruto/Minato Namikaze/image_5.webp',
    'assets/images/naruto/Minato Namikaze/image_6.webp',
    'assets/images/naruto/Minato Namikaze/image_7.webp',
    'assets/images/naruto/Minato Namikaze/image_8.webp',
    'assets/images/naruto/Minato Namikaze/image_9.webp',
    // Might Guy
    'assets/images/naruto/Might Guy/image_1.webp',
    'assets/images/naruto/Might Guy/image_2.webp',
    'assets/images/naruto/Might Guy/image_3.webp',
    'assets/images/naruto/Might Guy/image_4.webp',
    'assets/images/naruto/Might Guy/image_5.webp',
    'assets/images/naruto/Might Guy/image_6.webp',
    'assets/images/naruto/Might Guy/image_7.webp',
    'assets/images/naruto/Might Guy/image_8.webp',
    'assets/images/naruto/Might Guy/image_9.webp',
    'assets/images/naruto/Might Guy/image_10.webp',
    // Madara Uchiha
    'assets/images/naruto/Madara Uchiha/image_1.webp',
    'assets/images/naruto/Madara Uchiha/image_2.webp',
    'assets/images/naruto/Madara Uchiha/image_3.webp',
    'assets/images/naruto/Madara Uchiha/image_4.webp',
    'assets/images/naruto/Madara Uchiha/image_5.webp',
    'assets/images/naruto/Madara Uchiha/image_6.webp',
    // Konohamaru Sarutobi
    'assets/images/naruto/Konohamaru Sarutobi/image_1.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_2.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_3.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_4.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_5.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_6.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_7.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_8.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_9.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_10.webp',
    // Kiba Inuzuka
    'assets/images/naruto/Kiba Inuzuka/image_1.webp',
    'assets/images/naruto/Kiba Inuzuka/image_2.webp',
    'assets/images/naruto/Kiba Inuzuka/image_3.webp',
    'assets/images/naruto/Kiba Inuzuka/image_4.webp',
    'assets/images/naruto/Kiba Inuzuka/image_5.webp',
    'assets/images/naruto/Kiba Inuzuka/image_6.webp',
    'assets/images/naruto/Kiba Inuzuka/image_7.webp',
    'assets/images/naruto/Kiba Inuzuka/image_8.webp',
    'assets/images/naruto/Kiba Inuzuka/image_9.webp',
    'assets/images/naruto/Kiba Inuzuka/image_10.webp',
    // Kakashi Hatake
    'assets/images/naruto/Kakashi Hatake/image_1.webp',
    'assets/images/naruto/Kakashi Hatake/image_2.webp',
    'assets/images/naruto/Kakashi Hatake/image_3.webp',
    'assets/images/naruto/Kakashi Hatake/image_4.webp',
    'assets/images/naruto/Kakashi Hatake/image_5.webp',
    'assets/images/naruto/Kakashi Hatake/image_6.webp',
    'assets/images/naruto/Kakashi Hatake/image_7.webp',
    'assets/images/naruto/Kakashi Hatake/image_8.webp',
    // Jiraiya
    'assets/images/naruto/Jiraiya/image_1.webp',
    'assets/images/naruto/Jiraiya/image_2.webp',
    'assets/images/naruto/Jiraiya/image_3.webp',
    'assets/images/naruto/Jiraiya/image_4.webp',
    'assets/images/naruto/Jiraiya/image_5.webp',
    'assets/images/naruto/Jiraiya/image_6.webp',
    'assets/images/naruto/Jiraiya/image_7.webp',
    'assets/images/naruto/Jiraiya/image_8.webp',
    'assets/images/naruto/Jiraiya/image_9.webp',
    'assets/images/naruto/Jiraiya/image_10.webp',
    // Itachi Uchiha
    'assets/images/naruto/Itachi Uchiha/image_1.webp',
    'assets/images/naruto/Itachi Uchiha/image_2.webp',
    'assets/images/naruto/Itachi Uchiha/image_3.webp',
    'assets/images/naruto/Itachi Uchiha/image_4.webp',
    'assets/images/naruto/Itachi Uchiha/image_5.webp',
    'assets/images/naruto/Itachi Uchiha/image_6.webp',
    'assets/images/naruto/Itachi Uchiha/image_7.webp',
    'assets/images/naruto/Itachi Uchiha/image_8.webp',
    'assets/images/naruto/Itachi Uchiha/image_9.webp',
    'assets/images/naruto/Itachi Uchiha/image_10.webp',
    // Hiruzen Sarutobi
    'assets/images/naruto/Hiruzen Sarutobi/image_1.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_2.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_3.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_4.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_5.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_6.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_7.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_8.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_9.webp',
    // Gaara
    'assets/images/naruto/Gaara/image_1.webp',
    'assets/images/naruto/Gaara/image_2.webp',
    'assets/images/naruto/Gaara/image_3.webp',
    'assets/images/naruto/Gaara/image_4.webp',
    'assets/images/naruto/Gaara/image_5.webp',
    'assets/images/naruto/Gaara/image_6.webp',
    'assets/images/naruto/Gaara/image_7.webp',
    'assets/images/naruto/Gaara/image_8.webp',
    'assets/images/naruto/Gaara/image_9.webp',
    'assets/images/naruto/Gaara/image_10.webp',
    // Tsunade
    'assets/images/naruto/Tsunade/image_1.webp',
    'assets/images/naruto/Tsunade/image_2.webp',
    'assets/images/naruto/Tsunade/image_3.webp',
    'assets/images/naruto/Tsunade/image_4.webp',
    'assets/images/naruto/Tsunade/image_5.webp',
    'assets/images/naruto/Tsunade/image_6.webp',
    'assets/images/naruto/Tsunade/image_7.webp',
    'assets/images/naruto/Tsunade/image_8.webp',
    'assets/images/naruto/Tsunade/image_9.webp',
    // Shikamaru Nara
    'assets/images/naruto/Shikamaru Nara/image_1.webp',
    'assets/images/naruto/Shikamaru Nara/image_2.webp',
    'assets/images/naruto/Shikamaru Nara/image_3.webp',
    'assets/images/naruto/Shikamaru Nara/image_4.webp',
    'assets/images/naruto/Shikamaru Nara/image_5.webp',
    'assets/images/naruto/Shikamaru Nara/image_6.webp',
    'assets/images/naruto/Shikamaru Nara/image_7.webp',
    'assets/images/naruto/Shikamaru Nara/image_8.webp',
    'assets/images/naruto/Shikamaru Nara/image_9.webp',
    'assets/images/naruto/Shikamaru Nara/image_10.webp',
    // Sasuke Uchiha
    'assets/images/naruto/Sasuke Uchiha/image_1.webp',
    'assets/images/naruto/Sasuke Uchiha/image_2.webp',
    'assets/images/naruto/Sasuke Uchiha/image_3.webp',
    'assets/images/naruto/Sasuke Uchiha/image_4.webp',
    'assets/images/naruto/Sasuke Uchiha/image_5.webp',
    'assets/images/naruto/Sasuke Uchiha/image_6.webp',
    'assets/images/naruto/Sasuke Uchiha/image_7.webp',
    'assets/images/naruto/Sasuke Uchiha/image_8.webp',
    'assets/images/naruto/Sasuke Uchiha/image_9.webp',
    // Sakura Haruno
    'assets/images/naruto/Sakura Haruno/image_1.webp',
    'assets/images/naruto/Sakura Haruno/image_2.webp',
    'assets/images/naruto/Sakura Haruno/image_3.webp',
    'assets/images/naruto/Sakura Haruno/image_4.webp',
    'assets/images/naruto/Sakura Haruno/image_5.webp',
    'assets/images/naruto/Sakura Haruno/image_6.webp',
    'assets/images/naruto/Sakura Haruno/image_7.webp',
    'assets/images/naruto/Sakura Haruno/image_8.webp',
    'assets/images/naruto/Sakura Haruno/image_9.webp',
    'assets/images/naruto/Sakura Haruno/image_10.webp',
    'assets/images/naruto/Sakura Haruno/image_11.webp',
    'assets/images/naruto/Sakura Haruno/image_12.webp',
    // Rock Lee
    'assets/images/naruto/Rock Lee/image_1.webp',
    'assets/images/naruto/Rock Lee/image_2.webp',
    'assets/images/naruto/Rock Lee/image_3.webp',
    'assets/images/naruto/Rock Lee/image_4.webp',
    'assets/images/naruto/Rock Lee/image_5.webp',
    'assets/images/naruto/Rock Lee/image_6.webp',
    'assets/images/naruto/Rock Lee/image_7.webp',
  ],
  'Attack on Titan': [
    // Annie LEONHART
    'assets/images/attack_on_titan/Annie LEONHART/image_1.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_2.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_3.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_4.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_5.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_6.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_7.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_8.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_9.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_10.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_11.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_12.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_13.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_14.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_15.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_16.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_17.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_18.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_19.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_20.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_21.webp',
    // Armin ARLERT
    'assets/images/attack_on_titan/Armin ARLERT/image_1.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_2.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_3.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_4.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_5.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_6.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_7.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_8.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_9.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_10.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_11.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_12.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_13.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_14.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_15.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_16.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_17.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_18.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_19.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_20.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_21.webp',
    // Bertholdt HOOVER
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_1.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_2.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_3.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_4.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_5.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_6.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_7.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_8.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_9.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_10.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_11.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_12.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_13.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_14.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_15.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_16.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_17.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_18.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_19.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_20.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_21.webp',
    // Conny SPRINGER
    'assets/images/attack_on_titan/Conny SPRINGER/image_1.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_2.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_3.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_4.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_5.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_6.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_7.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_8.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_9.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_10.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_11.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_12.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_13.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_14.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_15.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_16.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_17.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_18.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_19.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_20.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_21.webp',
    // Dot PYXIS
    'assets/images/attack_on_titan/Dot PYXIS/image_1.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_2.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_3.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_4.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_5.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_6.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_7.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_8.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_9.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_10.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_11.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_12.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_13.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_14.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_15.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_16.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_17.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_18.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_19.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_20.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_21.webp',
    // Eld GIN
    'assets/images/attack_on_titan/Eld GIN/image_1.webp',
    'assets/images/attack_on_titan/Eld GIN/image_2.webp',
    'assets/images/attack_on_titan/Eld GIN/image_3.webp',
    'assets/images/attack_on_titan/Eld GIN/image_4.webp',
    'assets/images/attack_on_titan/Eld GIN/image_5.webp',
    'assets/images/attack_on_titan/Eld GIN/image_6.webp',
    'assets/images/attack_on_titan/Eld GIN/image_7.webp',
    'assets/images/attack_on_titan/Eld GIN/image_8.webp',
    'assets/images/attack_on_titan/Eld GIN/image_9.webp',
    'assets/images/attack_on_titan/Eld GIN/image_10.webp',
    'assets/images/attack_on_titan/Eld GIN/image_11.webp',
    'assets/images/attack_on_titan/Eld GIN/image_12.webp',
    'assets/images/attack_on_titan/Eld GIN/image_13.webp',
    'assets/images/attack_on_titan/Eld GIN/image_14.webp',
    'assets/images/attack_on_titan/Eld GIN/image_15.webp',
    'assets/images/attack_on_titan/Eld GIN/image_16.webp',
    'assets/images/attack_on_titan/Eld GIN/image_17.webp',
    'assets/images/attack_on_titan/Eld GIN/image_18.webp',
    'assets/images/attack_on_titan/Eld GIN/image_19.webp',
    'assets/images/attack_on_titan/Eld GIN/image_20.webp',
    'assets/images/attack_on_titan/Eld GIN/image_21.webp',
    // Eren YAEGER
    'assets/images/attack_on_titan/Eren YAEGER/image_1.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_2.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_3.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_4.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_5.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_6.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_7.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_8.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_9.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_10.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_11.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_12.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_13.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_14.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_15.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_16.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_17.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_18.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_19.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_20.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_21.webp',
    // Erwin SMITH
    'assets/images/attack_on_titan/Erwin SMITH/image_1.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_2.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_3.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_4.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_5.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_6.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_7.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_8.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_9.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_10.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_11.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_12.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_13.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_14.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_15.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_16.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_17.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_18.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_19.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_20.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_21.webp',
    // Gunther SCHULTZ
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_1.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_2.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_3.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_4.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_5.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_6.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_7.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_8.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_9.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_10.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_11.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_12.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_13.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_14.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_15.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_16.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_17.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_18.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_19.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_20.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_21.webp',
    // Hange ZOE
    'assets/images/attack_on_titan/Hange ZOE/image_1.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_2.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_3.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_4.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_5.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_6.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_7.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_8.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_9.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_10.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_11.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_12.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_13.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_14.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_15.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_16.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_17.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_18.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_19.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_20.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_21.webp',
    // Hannes
    'assets/images/attack_on_titan/Hannes/image_1.webp',
    'assets/images/attack_on_titan/Hannes/image_2.webp',
    'assets/images/attack_on_titan/Hannes/image_3.webp',
    'assets/images/attack_on_titan/Hannes/image_4.webp',
    'assets/images/attack_on_titan/Hannes/image_5.webp',
    'assets/images/attack_on_titan/Hannes/image_6.webp',
    'assets/images/attack_on_titan/Hannes/image_7.webp',
    'assets/images/attack_on_titan/Hannes/image_8.webp',
    'assets/images/attack_on_titan/Hannes/image_9.webp',
    'assets/images/attack_on_titan/Hannes/image_10.webp',
    'assets/images/attack_on_titan/Hannes/image_11.webp',
    'assets/images/attack_on_titan/Hannes/image_12.webp',
    'assets/images/attack_on_titan/Hannes/image_13.webp',
    'assets/images/attack_on_titan/Hannes/image_14.webp',
    'assets/images/attack_on_titan/Hannes/image_15.webp',
    'assets/images/attack_on_titan/Hannes/image_16.webp',
    'assets/images/attack_on_titan/Hannes/image_17.webp',
    'assets/images/attack_on_titan/Hannes/image_18.webp',
    'assets/images/attack_on_titan/Hannes/image_19.webp',
    'assets/images/attack_on_titan/Hannes/image_20.webp',
    'assets/images/attack_on_titan/Hannes/image_21.webp',
    // Jean KIRSCHTEIN
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_1.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_2.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_3.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_4.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_5.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_6.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_7.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_8.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_9.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_10.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_11.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_12.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_13.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_14.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_15.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_16.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_17.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_18.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_19.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_20.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_21.webp',
    // Levi ACKERMAN
    'assets/images/attack_on_titan/Levi ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_5.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_6.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_7.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_8.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_9.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_10.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_11.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_12.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_13.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_14.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_15.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_16.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_17.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_18.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_19.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_20.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_21.webp',
    // Marco BODT
    'assets/images/attack_on_titan/Marco BODT/image_1.webp',
    'assets/images/attack_on_titan/Marco BODT/image_2.webp',
    'assets/images/attack_on_titan/Marco BODT/image_3.webp',
    'assets/images/attack_on_titan/Marco BODT/image_4.webp',
    'assets/images/attack_on_titan/Marco BODT/image_5.webp',
    'assets/images/attack_on_titan/Marco BODT/image_6.webp',
    'assets/images/attack_on_titan/Marco BODT/image_7.webp',
    'assets/images/attack_on_titan/Marco BODT/image_8.webp',
    'assets/images/attack_on_titan/Marco BODT/image_9.webp',
    'assets/images/attack_on_titan/Marco BODT/image_10.webp',
    // Mikasa ACKERMAN
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_5.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_6.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_7.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_8.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_9.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_10.webp',
  ],
  'Black Clover': [],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Demon Slayer': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
  'Hunter X Hunter': [
    // Pariston Hill
    'assets/images/hunter_x_hunter/Pariston Hill/image_1.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_2.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_3.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_4.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_5.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_6.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_7.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_8.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_9.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_10.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_11.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_12.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_13.webp',
    // Morel Mackernasey
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_1.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_2.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_3.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_4.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_5.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_6.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_7.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_8.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_9.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_10.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_11.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_12.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_13.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_14.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_15.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_16.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_17.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_18.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_19.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_20.webp',
    // Isaac Netero
    'assets/images/hunter_x_hunter/Isaac Netero/image_1.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_2.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_3.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_4.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_5.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_6.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_7.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_8.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_9.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_10.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_11.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_12.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_13.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_14.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_15.webp',
    // Illumi Zoldyck
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_1.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_2.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_3.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_4.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_5.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_6.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_7.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_8.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_9.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_10.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_11.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_12.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_13.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_14.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_15.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_16.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_17.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_18.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_19.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_20.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_21.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_22.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_23.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_24.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_25.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_26.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_27.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_28.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_29.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_30.webp',
    // Hisoka Morow
    'assets/images/hunter_x_hunter/Hisoka Morow/image_1.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_2.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_3.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_4.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_5.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_6.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_7.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_8.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_9.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_10.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_11.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_12.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_13.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_14.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_15.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_16.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_17.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_18.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_19.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_20.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_21.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_22.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_23.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_24.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_25.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_26.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_27.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_28.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_29.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_30.webp',
    // Gon Freecss
    'assets/images/hunter_x_hunter/Gon Freecss/image_1.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_2.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_3.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_4.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_5.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_6.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_7.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_8.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_9.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_10.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_11.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_12.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_13.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_14.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_15.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_16.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_17.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_18.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_19.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_20.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_21.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_22.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_23.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_24.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_25.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_26.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_27.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_28.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_29.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_30.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_31.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_32.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_33.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_34.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_35.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_36.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_37.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_38.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_39.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_40.webp',
    // Ging Freecss
    'assets/images/hunter_x_hunter/Ging Freecss/image_1.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_2.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_3.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_4.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_5.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_6.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_7.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_8.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_9.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_10.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_11.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_12.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_13.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_14.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_15.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_16.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_17.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_18.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_19.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_20.webp',
    // Biscuit Krueger
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_1.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_2.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_3.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_4.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_5.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_6.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_7.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_8.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_9.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_10.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_11.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_12.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_13.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_14.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_15.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_16.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_17.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_18.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_19.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_20.webp',
    // كيلوا
    'assets/images/hunter_x_hunter/كيلوا/image_1.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_2.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_3.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_4.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_5.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_6.webp',
    // كيكيو زولديك
    'assets/images/hunter_x_hunter/كيكيو زولديك/image_1.webp',
    'assets/images/hunter_x_hunter/كيكيو زولديك/image_2.webp',
    // كوموغي
    'assets/images/hunter_x_hunter/كوموغي/image_1.webp',
    'assets/images/hunter_x_hunter/كوموغي/image_2.webp',
    // كولت
    'assets/images/hunter_x_hunter/كولت/image_1.webp',
    'assets/images/hunter_x_hunter/كولت/image_2.webp',
    // كورولو
    'assets/images/hunter_x_hunter/كورولو/image_1.webp',
    'assets/images/hunter_x_hunter/كورولو/image_2.webp',
    // كوروتوبي
    'assets/images/hunter_x_hunter/كوروتوبي/image_1.webp',
    'assets/images/hunter_x_hunter/كوروتوبي/image_2.webp',
    // كورابيكا
    'assets/images/hunter_x_hunter/كورابيكا/image_1.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_2.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_3.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_4.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_6.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_7.webp',
    // كلوك (الدجاجة)
    'assets/images/hunter_x_hunter/كلوك (الدجاجة)/image_1.webp',
    'assets/images/hunter_x_hunter/كلوك (الدجاجة)/image_2.webp',
    // كايتو
    'assets/images/hunter_x_hunter/كايتو/image_1.webp',
    'assets/images/hunter_x_hunter/كايتو/image_2.webp',
    // كانزاي (النمر)
    'assets/images/hunter_x_hunter/كانزاي (النمر)/image_1.webp',
    'assets/images/hunter_x_hunter/كانزاي (النمر)/image_3.webp',
    // كاناري
    'assets/images/hunter_x_hunter/كاناري/image_1.webp',
    'assets/images/hunter_x_hunter/كاناري/image_3.webp',
    'assets/images/hunter_x_hunter/كاناري/image_4.webp',
    // كاسترو
    'assets/images/hunter_x_hunter/كاسترو/image_1.webp',
    'assets/images/hunter_x_hunter/كاسترو/image_3.webp',
    // كالوتو
    'assets/images/hunter_x_hunter/كالوتو/image_1.webp',
    'assets/images/hunter_x_hunter/كالوتو/image_2.webp',
    // فيتان
    'assets/images/hunter_x_hunter/فيتان/image_1.webp',
    'assets/images/hunter_x_hunter/فيتان/image_2.webp',
    // فينيكس
    'assets/images/hunter_x_hunter/فينيكس/image_1.webp',
    'assets/images/hunter_x_hunter/فينيكس/image_3.webp',
    // فرانكلين
    'assets/images/hunter_x_hunter/فرانكلين/image_1.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_2.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_3.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_5.webp',
    // غينثرو
    'assets/images/hunter_x_hunter/غينثرو/image_1.webp',
    'assets/images/hunter_x_hunter/غينثرو/image_3.webp',
    'assets/images/hunter_x_hunter/غينثرو/image_4.webp',
    // غينتا (الخروف)
    'assets/images/hunter_x_hunter/غينتا (الخروف)/image_1.webp',
    'assets/images/hunter_x_hunter/غينتا (الخروف)/image_2.webp',
    // غيرو (الافعى)
    'assets/images/hunter_x_hunter/غيرو (الافعى)/image_1.webp',
    'assets/images/hunter_x_hunter/غيرو (الافعى)/image_2.webp',
    // غورينو
    'assets/images/hunter_x_hunter/غورينو/image_1.webp',
    'assets/images/hunter_x_hunter/غورينو/image_2.webp',
    // غيدو
    'assets/images/hunter_x_hunter/غيدو/image_1.webp',
    'assets/images/hunter_x_hunter/غيدو/image_2.webp',
    // غوتوه
    'assets/images/hunter_x_hunter/غوتوه/image_1.webp',
    'assets/images/hunter_x_hunter/غوتوه/image_2.webp',
    // شيزوكو
    'assets/images/hunter_x_hunter/شيزوكو/image_1.webp',
    'assets/images/hunter_x_hunter/شيزوكو/image_2.webp',
    // شيدور
    'assets/images/hunter_x_hunter/شيدور/image_1.webp',
    'assets/images/hunter_x_hunter/شيدور/image_2.webp',
    // شوت
    'assets/images/hunter_x_hunter/شوت/image_1.webp',
    'assets/images/hunter_x_hunter/شوت/image_3.webp',
    'assets/images/hunter_x_hunter/شوت/image_4.webp',
    // شالناك
    'assets/images/hunter_x_hunter/شالناك/image_1.webp',
    'assets/images/hunter_x_hunter/شالناك/image_2.webp',
    // سيلفا
    'assets/images/hunter_x_hunter/سيلفا/image_1.webp',
    'assets/images/hunter_x_hunter/سيلفا/image_2.webp',
    // شاسمونو
    'assets/images/hunter_x_hunter/شاسمونو/image_1.webp',
    'assets/images/hunter_x_hunter/شاسمونو/image_2.webp',
    // سكوالا
    'assets/images/hunter_x_hunter/سكوالا/image_1.webp',
    'assets/images/hunter_x_hunter/سكوالا/image_2.webp',
    // ساييو (القرد)
    'assets/images/hunter_x_hunter/ساييو (القرد)/image_1.webp',
    'assets/images/hunter_x_hunter/ساييو (القرد)/image_2.webp',
    // ساداسو
    'assets/images/hunter_x_hunter/ساداسو/image_1.webp',
    'assets/images/hunter_x_hunter/ساداسو/image_2.webp',
    // ساتوتز
    'assets/images/hunter_x_hunter/ساتوتز/image_1.webp',
    'assets/images/hunter_x_hunter/ساتوتز/image_2.webp',
    // ساتشو (الحصان)
    'assets/images/hunter_x_hunter/ساتشو (الحصان)/image_1.webp',
    'assets/images/hunter_x_hunter/ساتشو (الحصان)/image_2.webp',
    // زينو زولديك
    'assets/images/hunter_x_hunter/زينو زولديك/image_1.webp',
    'assets/images/hunter_x_hunter/زينو زولديك/image_3.webp',
    'assets/images/hunter_x_hunter/زينو زولديك/image_4.webp',
    // ساب
    'assets/images/hunter_x_hunter/ساب/image_1.webp',
    'assets/images/hunter_x_hunter/ساب/image_2.webp',
    // زيبرو
    'assets/images/hunter_x_hunter/زيبرو/image_1.webp',
    'assets/images/hunter_x_hunter/زيبرو/image_2.webp',
    // زيبايل
    'assets/images/hunter_x_hunter/زيبايل/image_1.webp',
    'assets/images/hunter_x_hunter/زيبايل/image_2.webp',
    // زازان
    'assets/images/hunter_x_hunter/زازان/image_1.webp',
    'assets/images/hunter_x_hunter/زازان/image_2.webp',
    // زوشي
    'assets/images/hunter_x_hunter/زوشي/image_1.webp',
    'assets/images/hunter_x_hunter/زوشي/image_2.webp',
    // ريفليت
    'assets/images/hunter_x_hunter/ريفليت/image_1.webp',
    'assets/images/hunter_x_hunter/ريفليت/image_2.webp',
    // رينا
    'assets/images/hunter_x_hunter/رينا/image_1.webp',
    'assets/images/hunter_x_hunter/رينا/image_2.webp',
    // راموت
    'assets/images/hunter_x_hunter/راموت/image_1.webp',
    'assets/images/hunter_x_hunter/راموت/image_2.webp',
    // ريزر
    'assets/images/hunter_x_hunter/ريزر/image_1.webp',
    'assets/images/hunter_x_hunter/ريزر/image_2.webp',
    // جين (الخنزير)
    'assets/images/hunter_x_hunter/جين (الخنزير)/image_1.webp',
    'assets/images/hunter_x_hunter/جين (الخنزير)/image_2.webp',
    // دالزولين
    'assets/images/hunter_x_hunter/دالزولين/image_1.webp',
    'assets/images/hunter_x_hunter/دالزولين/image_2.webp',
    // جون
    'assets/images/hunter_x_hunter/جون/image_1.webp',
    'assets/images/hunter_x_hunter/جون/image_2.webp',
    'assets/images/hunter_x_hunter/جون/image_3.webp',
    'assets/images/hunter_x_hunter/جون/image_4.webp',
    'assets/images/hunter_x_hunter/جون/image_5.webp',
    'assets/images/hunter_x_hunter/جون/image_7.webp',
    // تومبا
    'assets/images/hunter_x_hunter/تومبا/image_1.webp',
    'assets/images/hunter_x_hunter/تومبا/image_2.webp',
    // جايرو
    'assets/images/hunter_x_hunter/جايرو/image_1.webp',
    'assets/images/hunter_x_hunter/جايرو/image_2.webp',
    // تشيدل (الكلب)
    'assets/images/hunter_x_hunter/تشيدل (الكلب)/image_1.webp',
    'assets/images/hunter_x_hunter/تشيدل (الكلب)/image_2.webp',
    // تشيتو
    'assets/images/hunter_x_hunter/تشيتو/image_1.webp',
    'assets/images/hunter_x_hunter/تشيتو/image_2.webp',
    // تسيزوجيرا
    'assets/images/hunter_x_hunter/تسيزوجيرا/image_1.webp',
    'assets/images/hunter_x_hunter/تسيزوجيرا/image_2.webp',
    // بيون (الارنب)
    'assets/images/hunter_x_hunter/بيون (الارنب)/image_1.webp',
    'assets/images/hunter_x_hunter/بيون (الارنب)/image_2.webp',
    // تسوبوني
    'assets/images/hunter_x_hunter/تسوبوني/image_1.webp',
    'assets/images/hunter_x_hunter/تسوبوني/image_2.webp',
    // بينورينوفو
    'assets/images/hunter_x_hunter/بينورينوفو/image_1.webp',
    'assets/images/hunter_x_hunter/بينورينوفو/image_2.webp',
    // بينولت
    'assets/images/hunter_x_hunter/بينولت/image_1.webp',
    'assets/images/hunter_x_hunter/بينولت/image_2.webp',
    // بيزي
    'assets/images/hunter_x_hunter/بيزي/image_1.webp',
    'assets/images/hunter_x_hunter/بيزي/image_2.webp',
    // بيسكي
    'assets/images/hunter_x_hunter/بيسكي/image_1.webp',
    'assets/images/hunter_x_hunter/بيسكي/image_2.webp',
    // بينز
    'assets/images/hunter_x_hunter/بينز/image_1.webp',
    'assets/images/hunter_x_hunter/بينز/image_2.webp',
    // بوهارا
    'assets/images/hunter_x_hunter/بوهارا/image_1.webp',
    'assets/images/hunter_x_hunter/بوهارا/image_2.webp',
    // بيتو
    'assets/images/hunter_x_hunter/بيتو/image_1.webp',
    'assets/images/hunter_x_hunter/بيتو/image_2.webp',
    // بوكي
    'assets/images/hunter_x_hunter/بوكي/image_1.webp',
    'assets/images/hunter_x_hunter/بوكي/image_2.webp',
    // بونزو
    'assets/images/hunter_x_hunter/بونزو/image_1.webp',
    'assets/images/hunter_x_hunter/بونزو/image_2.webp',
    // بوف
    'assets/images/hunter_x_hunter/بوف/image_1.webp',
    'assets/images/hunter_x_hunter/بوف/image_2.webp',
    // بوكل
    'assets/images/hunter_x_hunter/بوكل/image_1.webp',
    'assets/images/hunter_x_hunter/بوكل/image_2.webp',
    // بوبوبو
    'assets/images/hunter_x_hunter/بوبوبو/image_1.webp',
    'assets/images/hunter_x_hunter/بوبوبو/image_2.webp',
    // بوتوباي (التنين)
    'assets/images/hunter_x_hunter/بوتوباي (التنين)/image_1.webp',
    'assets/images/hunter_x_hunter/بوتوباي (التنين)/image_2.webp',
    // بايرو
    'assets/images/hunter_x_hunter/بايرو/image_1.webp',
    'assets/images/hunter_x_hunter/بايرو/image_2.webp',
    // بايك
    'assets/images/hunter_x_hunter/بايك/image_1.webp',
    'assets/images/hunter_x_hunter/بايك/image_2.webp',
    // بالم
    'assets/images/hunter_x_hunter/بالم/image_1.webp',
    'assets/images/hunter_x_hunter/بالم/image_2.webp',
    // باشو
    'assets/images/hunter_x_hunter/باشو/image_1.webp',
    'assets/images/hunter_x_hunter/باشو/image_2.webp',
    // باكونودا
    'assets/images/hunter_x_hunter/باكونودا/image_1.webp',
    'assets/images/hunter_x_hunter/باكونودا/image_2.webp',
    // باريستون (الفأر)
    'assets/images/hunter_x_hunter/باريستون (الفأر)/image_1.webp',
    'assets/images/hunter_x_hunter/باريستون (الفأر)/image_2.webp',
    // ايلومي
    'assets/images/hunter_x_hunter/ايلومي/image_1.webp',
    'assets/images/hunter_x_hunter/ايلومي/image_2.webp',
    // بارا
    'assets/images/hunter_x_hunter/بارا/image_1.webp',
    'assets/images/hunter_x_hunter/بارا/image_2.webp',
    // ايكالغوا
    'assets/images/hunter_x_hunter/ايكالغوا/image_1.webp',
    'assets/images/hunter_x_hunter/ايكالغوا/image_2.webp',
    // اوبوغين
    'assets/images/hunter_x_hunter/اوبوغين/image_1.webp',
    // ايزانوبي
    'assets/images/hunter_x_hunter/ايزانوبي/image_1.webp',
    // أماني
    'assets/images/hunter_x_hunter/أماني/image_1.webp',
    'assets/images/hunter_x_hunter/أماني/image_2.webp',
    // ألوكا
    'assets/images/hunter_x_hunter/ألوكا/image_1.webp',
    'assets/images/hunter_x_hunter/ألوكا/image_2.webp',
    // الاخوان اورثو
    'assets/images/hunter_x_hunter/الاخوان اورثو/image_1.webp',
    'assets/images/hunter_x_hunter/الاخوان اورثو/image_2.webp',
    // ابينغاني
    'assets/images/hunter_x_hunter/ابينغاني/image_1.webp',
    'assets/images/hunter_x_hunter/ابينغاني/image_2.webp',
    // يوبي
    'assets/images/hunter_x_hunter/يوبي/image_1.webp',
    'assets/images/hunter_x_hunter/يوبي/image_2.webp',
    // ويلفن
    'assets/images/hunter_x_hunter/ويلفن/image_1.webp',
    'assets/images/hunter_x_hunter/ويلفن/image_2.webp',
    // وينغ
    'assets/images/hunter_x_hunter/وينغ/image_1.webp',
    'assets/images/hunter_x_hunter/وينغ/image_2.webp',
    // هيسوكا
    'assets/images/hunter_x_hunter/هيسوكا/image_1.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_2.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_3.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_5.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_6.webp',
    // هانزو
    'assets/images/hunter_x_hunter/هانزو/image_1.webp',
    'assets/images/hunter_x_hunter/هانزو/image_2.webp',
    // نيون نوستراد
    'assets/images/hunter_x_hunter/نيون نوستراد/image_1.webp',
    'assets/images/hunter_x_hunter/نيون نوستراد/image_2.webp',
    // هارونا
    'assets/images/hunter_x_hunter/هارونا/image_1.webp',
    'assets/images/hunter_x_hunter/هارونا/image_2.webp',
    // نيتيرو
    'assets/images/hunter_x_hunter/نيتيرو/image_1.webp',
    'assets/images/hunter_x_hunter/نيتيرو/image_2.webp',
    // نوبوناغا
    'assets/images/hunter_x_hunter/نوبوناغا/image_1.webp',
    'assets/images/hunter_x_hunter/نوبوناغا/image_2.webp',
    // نوف
    'assets/images/hunter_x_hunter/نوف/image_1.webp',
    'assets/images/hunter_x_hunter/نوف/image_2.webp',
    // نانيكا
    'assets/images/hunter_x_hunter/نانيكا/image_1.webp',
    'assets/images/hunter_x_hunter/نانيكا/image_2.webp',
    // مينشي
    'assets/images/hunter_x_hunter/مينشي/image_1.webp',
    'assets/images/hunter_x_hunter/مينشي/image_3.webp',
    'assets/images/hunter_x_hunter/مينشي/image_4.webp',
    // ناكل
    'assets/images/hunter_x_hunter/ناكيل/image_1.webp',
    'assets/images/hunter_x_hunter/ناكيل/image_2.webp',
    // ميليورون
    'assets/images/hunter_x_hunter/ميليورون/image_1.webp',
    'assets/images/hunter_x_hunter/ميليورون/image_2.webp',
    // ميلودي
    'assets/images/hunter_x_hunter/ميلودي/image_1.webp',
    'assets/images/hunter_x_hunter/ميلودي/image_2.webp',
    // ميلوكي
    'assets/images/hunter_x_hunter/ميلوكي/image_1.webp',
    'assets/images/hunter_x_hunter/ميلوكي/image_2.webp',
    // ميزايستومو (البقرة)
    'assets/images/hunter_x_hunter/ميزايستومو (البقرة)/image_1.webp',
    'assets/images/hunter_x_hunter/ميزايستومو (البقرة)/image_2.webp',
    // ميرويم
    'assets/images/hunter_x_hunter/ميرويم/image_1.webp',
    'assets/images/hunter_x_hunter/ميرويم/image_2.webp',
    // ميتو
    'assets/images/hunter_x_hunter/ميتو/image_1.webp',
    'assets/images/hunter_x_hunter/ميتو/image_2.webp',
    // ملكة النمل
    'assets/images/hunter_x_hunter/ملكة النمل/image_1.webp',
    'assets/images/hunter_x_hunter/ملكة النمل/image_2.webp',
    // ليول
    'assets/images/hunter_x_hunter/ليول/image_1.webp',
    'assets/images/hunter_x_hunter/ليول/image_2.webp',
    // ماتشي
    'assets/images/hunter_x_hunter/ماتشي/image_1.webp',
    'assets/images/hunter_x_hunter/ماتشي/image_2.webp',
    // ليوريو
    'assets/images/hunter_x_hunter/ليوريو/image_1.webp',
    'assets/images/hunter_x_hunter/ليوريو/image_2.webp',
    // ليبو
    'assets/images/hunter_x_hunter/ليبو/image_1.webp',
    'assets/images/hunter_x_hunter/ليبو/image_2.webp',
    // لايت نوستراد
    'assets/images/hunter_x_hunter/لايت نوستراد/image_1.webp',
    'assets/images/hunter_x_hunter/لايت نوستراد/image_2.webp',
    // لاتارزا
    'assets/images/hunter_x_hunter/لاتارزا/image_1.webp',
  ],
  'Jujutsu Kaisen': [],
  'My Hero Academia': [],
  'One Piece': [],
  'Solo Leveling': [],
  'Tokyo Revengers': [],
  'Vinland Saga': [],
};