const Map<String, List<String>> categoryAssets = {
  'Naruto': [
    'assets/images/naruto/Akamaru/image_1.webp',
    'assets/images/naruto/Akamaru/image_2.webp',
    'assets/images/naruto/Akamaru/image_3.webp',
    'assets/images/naruto/Akamaru/image_4.webp',
    'assets/images/naruto/Akamaru/image_5.webp',
    'assets/images/naruto/Choji Akimichi/image_1.webp',
    'assets/images/naruto/Choji Akimichi/image_2.webp',
    'assets/images/naruto/Choji Akimichi/image_3.webp',
    'assets/images/naruto/Choji Akimichi/image_4.webp',
    'assets/images/naruto/Choji Akimichi/image_5.webp',
    'assets/images/naruto/Gaara/image_1.webp',
    'assets/images/naruto/Gaara/image_2.webp',
    'assets/images/naruto/Gaara/image_3.webp',
    'assets/images/naruto/Gaara/image_4.webp',
    'assets/images/naruto/Gaara/image_5.webp',
    'assets/images/naruto/Hinata Hyuga/image_1.webp',
    'assets/images/naruto/Hinata Hyuga/image_2.webp',
    'assets/images/naruto/Hinata Hyuga/image_3.webp',
    'assets/images/naruto/Hinata Hyuga/image_4.webp',
    'assets/images/naruto/Hinata Hyuga/image_5.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_1.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_2.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_3.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_4.webp',
    'assets/images/naruto/Hiruzen Sarutobi/image_5.webp',
    'assets/images/naruto/Ino Yamanaka/image_1.webp',
    'assets/images/naruto/Ino Yamanaka/image_2.webp',
    'assets/images/naruto/Ino Yamanaka/image_3.webp',
    'assets/images/naruto/Ino Yamanaka/image_4.webp',
    'assets/images/naruto/Ino Yamanaka/image_5.webp',
    'assets/images/naruto/Itachi Uchiha/image_1.webp',
    'assets/images/naruto/Itachi Uchiha/image_2.webp',
    'assets/images/naruto/Itachi Uchiha/image_3.webp',
    'assets/images/naruto/Itachi Uchiha/image_4.webp',
    'assets/images/naruto/Itachi Uchiha/image_5.webp',
    'assets/images/naruto/Jiraiya/image_1.webp',
    'assets/images/naruto/Jiraiya/image_2.webp',
    'assets/images/naruto/Jiraiya/image_3.webp',
    'assets/images/naruto/Jiraiya/image_4.webp',
    'assets/images/naruto/Jiraiya/image_5.webp',
    'assets/images/naruto/Kakashi Hatake/image_1.webp',
    'assets/images/naruto/Kakashi Hatake/image_2.webp',
    'assets/images/naruto/Kakashi Hatake/image_3.webp',
    'assets/images/naruto/Kakashi Hatake/image_4.webp',
    'assets/images/naruto/Kakashi Hatake/image_5.webp',
    'assets/images/naruto/Kiba Inuzuka/image_1.webp',
    'assets/images/naruto/Kiba Inuzuka/image_2.webp',
    'assets/images/naruto/Kiba Inuzuka/image_3.webp',
    'assets/images/naruto/Kiba Inuzuka/image_4.webp',
    'assets/images/naruto/Kiba Inuzuka/image_5.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_1.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_2.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_3.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_4.webp',
    'assets/images/naruto/Konohamaru Sarutobi/image_5.webp',
    'assets/images/naruto/Madara Uchiha/image_1.webp',
    'assets/images/naruto/Madara Uchiha/image_2.webp',
    'assets/images/naruto/Madara Uchiha/image_3.webp',
    'assets/images/naruto/Madara Uchiha/image_4.webp',
    'assets/images/naruto/Madara Uchiha/image_5.webp',
    'assets/images/naruto/Might Guy/image_1.webp',
    'assets/images/naruto/Might Guy/image_2.webp',
    'assets/images/naruto/Might Guy/image_3.webp',
    'assets/images/naruto/Might Guy/image_4.webp',
    'assets/images/naruto/Might Guy/image_5.webp',
    'assets/images/naruto/Minato Namikaze/image_1.webp',
    'assets/images/naruto/Minato Namikaze/image_2.webp',
    'assets/images/naruto/Minato Namikaze/image_3.webp',
    'assets/images/naruto/Minato Namikaze/image_4.webp',
    'assets/images/naruto/Minato Namikaze/image_5.webp',
    'assets/images/naruto/Naruto Uzumaki/image_1.webp',
    'assets/images/naruto/Naruto Uzumaki/image_2.webp',
    'assets/images/naruto/Naruto Uzumaki/image_3.webp',
    'assets/images/naruto/Naruto Uzumaki/image_4.webp',
    'assets/images/naruto/Naruto Uzumaki/image_5.webp',
    'assets/images/naruto/Neji Hyuga/image_1.webp',
    'assets/images/naruto/Neji Hyuga/image_2.webp',
    'assets/images/naruto/Neji Hyuga/image_3.webp',
    'assets/images/naruto/Neji Hyuga/image_4.webp',
    'assets/images/naruto/Neji Hyuga/image_5.webp',
    'assets/images/naruto/Obito Uchiha/image_1.webp',
    'assets/images/naruto/Obito Uchiha/image_2.webp',
    'assets/images/naruto/Obito Uchiha/image_3.webp',
    'assets/images/naruto/Obito Uchiha/image_4.webp',
    'assets/images/naruto/Obito Uchiha/image_5.webp',
    'assets/images/naruto/Orochimaru/image_1.webp',
    'assets/images/naruto/Orochimaru/image_2.webp',
    'assets/images/naruto/Orochimaru/image_3.webp',
    'assets/images/naruto/Orochimaru/image_4.webp',
    'assets/images/naruto/Orochimaru/image_5.webp',
    'assets/images/naruto/Rock Lee/image_1.webp',
    'assets/images/naruto/Rock Lee/image_2.webp',
    'assets/images/naruto/Rock Lee/image_3.webp',
    'assets/images/naruto/Rock Lee/image_4.webp',
    'assets/images/naruto/Rock Lee/image_5.webp',
    'assets/images/naruto/Sakura Haruno/image_1.webp',
    'assets/images/naruto/Sakura Haruno/image_2.webp',
    'assets/images/naruto/Sakura Haruno/image_3.webp',
    'assets/images/naruto/Sakura Haruno/image_4.webp',
    'assets/images/naruto/Sakura Haruno/image_5.webp',
    'assets/images/naruto/Sasuke Uchiha/image_1.webp',
    'assets/images/naruto/Sasuke Uchiha/image_2.webp',
    'assets/images/naruto/Sasuke Uchiha/image_3.webp',
    'assets/images/naruto/Sasuke Uchiha/image_4.webp',
    'assets/images/naruto/Sasuke Uchiha/image_5.webp',
    'assets/images/naruto/Shikamaru Nara/image_1.webp',
    'assets/images/naruto/Shikamaru Nara/image_2.webp',
    'assets/images/naruto/Shikamaru Nara/image_3.webp',
    'assets/images/naruto/Shikamaru Nara/image_4.webp',
    'assets/images/naruto/Shikamaru Nara/image_5.webp',
    'assets/images/naruto/Shizune/image_1.webp',
    'assets/images/naruto/Shizune/image_2.webp',
    'assets/images/naruto/Shizune/image_3.webp',
    'assets/images/naruto/Shizune/image_4.webp',
    'assets/images/naruto/Shizune/image_5.webp',
    'assets/images/naruto/Tsunade/image_1.webp',
    'assets/images/naruto/Tsunade/image_2.webp',
    'assets/images/naruto/Tsunade/image_3.webp',
    'assets/images/naruto/Tsunade/image_4.webp',
    'assets/images/naruto/Tsunade/image_5.webp',
  ],
  'Attack on Titan': [
    'assets/images/attack_on_titan/Annie LEONHART/image_1.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_2.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_3.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_4.webp',
    'assets/images/attack_on_titan/Annie LEONHART/image_5.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_1.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_2.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_3.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_4.webp',
    'assets/images/attack_on_titan/Armin ARLERT/image_5.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_1.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_2.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_3.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_4.webp',
    'assets/images/attack_on_titan/Bertholdt HOOVER/image_5.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_1.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_2.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_3.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_4.webp',
    'assets/images/attack_on_titan/Conny SPRINGER/image_5.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_1.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_2.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_3.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_4.webp',
    'assets/images/attack_on_titan/Dot PYXIS/image_5.webp',
    'assets/images/attack_on_titan/Eld GIN/image_1.webp',
    'assets/images/attack_on_titan/Eld GIN/image_2.webp',
    'assets/images/attack_on_titan/Eld GIN/image_3.webp',
    'assets/images/attack_on_titan/Eld GIN/image_4.webp',
    'assets/images/attack_on_titan/Eld GIN/image_5.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_1.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_2.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_3.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_4.webp',
    'assets/images/attack_on_titan/Eren YAEGER/image_5.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_1.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_2.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_3.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_4.webp',
    'assets/images/attack_on_titan/Erwin SMITH/image_5.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_1.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_2.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_3.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_4.webp',
    'assets/images/attack_on_titan/Gunther SCHULTZ/image_5.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_1.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_2.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_3.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_4.webp',
    'assets/images/attack_on_titan/Hange ZOE/image_5.webp',
    'assets/images/attack_on_titan/Hannes/image_1.webp',
    'assets/images/attack_on_titan/Hannes/image_2.webp',
    'assets/images/attack_on_titan/Hannes/image_3.webp',
    'assets/images/attack_on_titan/Hannes/image_4.webp',
    'assets/images/attack_on_titan/Hannes/image_5.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_1.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_2.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_3.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_4.webp',
    'assets/images/attack_on_titan/Jean KIRSCHTEIN/image_5.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Levi ACKERMAN/image_5.webp',
    'assets/images/attack_on_titan/Marco BODT/image_1.webp',
    'assets/images/attack_on_titan/Marco BODT/image_2.webp',
    'assets/images/attack_on_titan/Marco BODT/image_3.webp',
    'assets/images/attack_on_titan/Marco BODT/image_4.webp',
    'assets/images/attack_on_titan/Marco BODT/image_5.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_1.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_2.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_3.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_4.webp',
    'assets/images/attack_on_titan/Mikasa ACKERMAN/image_5.webp',
  ],
  'Hunter X Hunter': [
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_1.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_2.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_3.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_4.webp',
    'assets/images/hunter_x_hunter/Biscuit Krueger/image_5.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_1.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_2.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_3.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_4.webp',
    'assets/images/hunter_x_hunter/Ging Freecss/image_5.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_1.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_2.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_3.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_4.webp',
    'assets/images/hunter_x_hunter/Gon Freecss/image_5.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_1.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_2.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_3.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_4.webp',
    'assets/images/hunter_x_hunter/Hisoka Morow/image_5.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_1.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_2.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_3.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_4.webp',
    'assets/images/hunter_x_hunter/Illumi Zoldyck/image_5.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_1.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_2.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_3.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_4.webp',
    'assets/images/hunter_x_hunter/Isaac Netero/image_5.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_1.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_2.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_3.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_4.webp',
    'assets/images/hunter_x_hunter/Morel Mackernasey/image_5.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_1.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_2.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_3.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_4.webp',
    'assets/images/hunter_x_hunter/Pariston Hill/image_5.webp',
    'assets/images/hunter_x_hunter/ألوكا/image_1.webp',
    'assets/images/hunter_x_hunter/أماني/image_1.webp',
    'assets/images/hunter_x_hunter/ابينغاني/image_1.webp',
    'assets/images/hunter_x_hunter/الاخوان اورثو/image_1.webp',
    'assets/images/hunter_x_hunter/اوبوغين/image_1.webp',
    'assets/images/hunter_x_hunter/ايزانوبي/image_1.webp',
    'assets/images/hunter_x_hunter/ايكالغوا/image_1.webp',
    'assets/images/hunter_x_hunter/ايلومي/image_1.webp',
    'assets/images/hunter_x_hunter/بارا/image_1.webp',
    'assets/images/hunter_x_hunter/باريستون (الفأر)/image_1.webp',
    'assets/images/hunter_x_hunter/باشو/image_1.webp',
    'assets/images/hunter_x_hunter/باكونودا/image_1.webp',
    'assets/images/hunter_x_hunter/بالم/image_1.webp',
    'assets/images/hunter_x_hunter/بالم/image_2.webp',
    'assets/images/hunter_x_hunter/بالم/image_4.webp',
    'assets/images/hunter_x_hunter/بايرو/image_1.webp',
    'assets/images/hunter_x_hunter/بايك/image_1.webp',
    'assets/images/hunter_x_hunter/بايك/image_2.webp',
    'assets/images/hunter_x_hunter/بوبوبو/image_1.webp',
    'assets/images/hunter_x_hunter/بوتوباي (التنين)/image_1.webp',
    'assets/images/hunter_x_hunter/بوف/image_1.webp',
    'assets/images/hunter_x_hunter/بوكل/image_1.webp',
    'assets/images/hunter_x_hunter/بوكي/image_1.webp',
    'assets/images/hunter_x_hunter/بوكي/image_3.webp',
    'assets/images/hunter_x_hunter/بونزو/image_1.webp',
    'assets/images/hunter_x_hunter/بوهارا/image_1.webp',
    'assets/images/hunter_x_hunter/بيتو/image_1.webp',
    'assets/images/hunter_x_hunter/بيزي/image_1.webp',
    'assets/images/hunter_x_hunter/بيزي/image_3.webp',
    'assets/images/hunter_x_hunter/بيسكي/image_1.webp',
    'assets/images/hunter_x_hunter/بيسكي/image_3.webp',
    'assets/images/hunter_x_hunter/بينز/image_1.webp',
    'assets/images/hunter_x_hunter/بينورينوفو/image_1.webp',
    'assets/images/hunter_x_hunter/بينولت/image_1.webp',
    'assets/images/hunter_x_hunter/بينولت/image_3.webp',
    'assets/images/hunter_x_hunter/بيون (الارنب)/image_1.webp',
    'assets/images/hunter_x_hunter/بيون (الارنب)/image_3.webp',
    'assets/images/hunter_x_hunter/تسوبوني/image_1.webp',
    'assets/images/hunter_x_hunter/تسيزوجيرا/image_1.webp',
    'assets/images/hunter_x_hunter/تسيزوجيرا/image_3.webp',
    'assets/images/hunter_x_hunter/تشيتو/image_1.webp',
    'assets/images/hunter_x_hunter/تشيتو/image_3.webp',
    'assets/images/hunter_x_hunter/تشيدل (الكلب)/image_1.webp',
    'assets/images/hunter_x_hunter/تشيدل (الكلب)/image_3.webp',
    'assets/images/hunter_x_hunter/تشيدل (الكلب)/image_4.webp',
    'assets/images/hunter_x_hunter/تومبا/image_1.webp',
    'assets/images/hunter_x_hunter/تومبا/image_3.webp',
    'assets/images/hunter_x_hunter/جايرو/image_1.webp',
    'assets/images/hunter_x_hunter/جايرو/image_2.webp',
    'assets/images/hunter_x_hunter/جون/image_1.webp',
    'assets/images/hunter_x_hunter/جون/image_2.webp',
    'assets/images/hunter_x_hunter/جون/image_3.webp',
    'assets/images/hunter_x_hunter/جون/image_4.webp',
    'assets/images/hunter_x_hunter/جون/image_5.webp',
    'assets/images/hunter_x_hunter/جون/image_7.webp',
    'assets/images/hunter_x_hunter/جين (الخنزير)/image_1.webp',
    'assets/images/hunter_x_hunter/جين (الخنزير)/image_2.webp',
    'assets/images/hunter_x_hunter/جين (الخنزير)/image_4.webp',
    'assets/images/hunter_x_hunter/دالزولين/image_1.webp',
    'assets/images/hunter_x_hunter/دالزولين/image_2.webp',
    'assets/images/hunter_x_hunter/راموت/image_1.webp',
    'assets/images/hunter_x_hunter/راموت/image_3.webp',
    'assets/images/hunter_x_hunter/راموت/image_4.webp',
    'assets/images/hunter_x_hunter/ريزر/image_1.webp',
    'assets/images/hunter_x_hunter/ريزر/image_2.webp',
    'assets/images/hunter_x_hunter/ريفليت/image_1.webp',
    'assets/images/hunter_x_hunter/رينا/image_1.webp',
    'assets/images/hunter_x_hunter/رينا/image_2.webp',
    'assets/images/hunter_x_hunter/زازان/image_1.webp',
    'assets/images/hunter_x_hunter/زازان/image_3.webp',
    'assets/images/hunter_x_hunter/زوشي/image_1.webp',
    'assets/images/hunter_x_hunter/زوشي/image_2.webp',
    'assets/images/hunter_x_hunter/زيبايل/image_1.webp',
    'assets/images/hunter_x_hunter/زيبايل/image_2.webp',
    'assets/images/hunter_x_hunter/زيبرو/image_1.webp',
    'assets/images/hunter_x_hunter/زيبرو/image_3.webp',
    'assets/images/hunter_x_hunter/زيبرو/image_4.webp',
    'assets/images/hunter_x_hunter/زينو زولديك/image_1.webp',
    'assets/images/hunter_x_hunter/زينو زولديك/image_3.webp',
    'assets/images/hunter_x_hunter/زينو زولديك/image_4.webp',
    'assets/images/hunter_x_hunter/ساب/image_1.webp',
    'assets/images/hunter_x_hunter/ساب/image_2.webp',
    'assets/images/hunter_x_hunter/ساتشو (الحصان)/image_1.webp',
    'assets/images/hunter_x_hunter/ساتشو (الحصان)/image_2.webp',
    'assets/images/hunter_x_hunter/ساتوتز/image_1.webp',
    'assets/images/hunter_x_hunter/ساتوتز/image_3.webp',
    'assets/images/hunter_x_hunter/ساتوتز/image_4.webp',
    'assets/images/hunter_x_hunter/ساداسو/image_1.webp',
    'assets/images/hunter_x_hunter/ساداسو/image_2.webp',
    'assets/images/hunter_x_hunter/ساييو (القرد)/image_1.webp',
    'assets/images/hunter_x_hunter/ساييو (القرد)/image_2.webp',
    'assets/images/hunter_x_hunter/سكوالا/image_1.webp',
    'assets/images/hunter_x_hunter/سكوالا/image_3.webp',
    'assets/images/hunter_x_hunter/سكوالا/image_4.webp',
    'assets/images/hunter_x_hunter/سيلفا/image_1.webp',
    'assets/images/hunter_x_hunter/سيلفا/image_2.webp',
    'assets/images/hunter_x_hunter/شاسمونو/image_1.webp',
    'assets/images/hunter_x_hunter/شاسمونو/image_3.webp',
    'assets/images/hunter_x_hunter/شالناك/image_1.webp',
    'assets/images/hunter_x_hunter/شالناك/image_2.webp',
    'assets/images/hunter_x_hunter/شالناك/image_3.webp',
    'assets/images/hunter_x_hunter/شوت/image_1.webp',
    'assets/images/hunter_x_hunter/شوت/image_2.webp',
    'assets/images/hunter_x_hunter/شوت/image_3.webp',
    'assets/images/hunter_x_hunter/شيدور/image_1.webp',
    'assets/images/hunter_x_hunter/شيدور/image_2.webp',
    'assets/images/hunter_x_hunter/شيدور/image_3.webp',
    'assets/images/hunter_x_hunter/شيزوكو/image_1.webp',
    'assets/images/hunter_x_hunter/شيزوكو/image_2.webp',
    'assets/images/hunter_x_hunter/شيزوكو/image_3.webp',
    'assets/images/hunter_x_hunter/غوتوه/image_1.webp',
    'assets/images/hunter_x_hunter/غوتوه/image_2.webp',
    'assets/images/hunter_x_hunter/غوتوه/image_3.webp',
    'assets/images/hunter_x_hunter/غورينو/image_1.webp',
    'assets/images/hunter_x_hunter/غورينو/image_2.webp',
    'assets/images/hunter_x_hunter/غورينو/image_3.webp',
    'assets/images/hunter_x_hunter/غيدو/image_1.webp',
    'assets/images/hunter_x_hunter/غيدو/image_2.webp',
    'assets/images/hunter_x_hunter/غيدو/image_3.webp',
    'assets/images/hunter_x_hunter/غيرو (الافعى)/image_1.webp',
    'assets/images/hunter_x_hunter/غيرو (الافعى)/image_2.webp',
    'assets/images/hunter_x_hunter/غيرو (الافعى)/image_3.webp',
    'assets/images/hunter_x_hunter/غينتا (الخروف)/image_1.webp',
    'assets/images/hunter_x_hunter/غينتا (الخروف)/image_2.webp',
    'assets/images/hunter_x_hunter/غينتا (الخروف)/image_3.webp',
    'assets/images/hunter_x_hunter/غينثرو/image_1.webp',
    'assets/images/hunter_x_hunter/غينثرو/image_2.webp',
    'assets/images/hunter_x_hunter/غينثرو/image_3.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_1.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_2.webp',
    'assets/images/hunter_x_hunter/فرانكلين/image_3.webp',
    'assets/images/hunter_x_hunter/فيتان/image_1.webp',
    'assets/images/hunter_x_hunter/فيتان/image_2.webp',
    'assets/images/hunter_x_hunter/فيتان/image_3.webp',
    'assets/images/hunter_x_hunter/فينيكس/image_1.webp',
    'assets/images/hunter_x_hunter/فينيكس/image_2.webp',
    'assets/images/hunter_x_hunter/فينيكس/image_3.webp',
    'assets/images/hunter_x_hunter/كاسترو/image_1.webp',
    'assets/images/hunter_x_hunter/كاسترو/image_2.webp',
    'assets/images/hunter_x_hunter/كاسترو/image_3.webp',
    'assets/images/hunter_x_hunter/كالوتو/image_1.webp',
    'assets/images/hunter_x_hunter/كالوتو/image_2.webp',
    'assets/images/hunter_x_hunter/كالوتو/image_3.webp',
    'assets/images/hunter_x_hunter/كاناري/image_1.webp',
    'assets/images/hunter_x_hunter/كاناري/image_2.webp',
    'assets/images/hunter_x_hunter/كاناري/image_3.webp',
    'assets/images/hunter_x_hunter/كانزاي (النمر)/image_1.webp',
    'assets/images/hunter_x_hunter/كانزاي (النمر)/image_2.webp',
    'assets/images/hunter_x_hunter/كانزاي (النمر)/image_3.webp',
    'assets/images/hunter_x_hunter/كايتو/image_1.webp',
    'assets/images/hunter_x_hunter/كايتو/image_2.webp',
    'assets/images/hunter_x_hunter/كايتو/image_3.webp',
    'assets/images/hunter_x_hunter/كلوك (الدجاجة)/image_1.webp',
    'assets/images/hunter_x_hunter/كلوك (الدجاجة)/image_2.webp',
    'assets/images/hunter_x_hunter/كلوك (الدجاجة)/image_3.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_1.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_2.webp',
    'assets/images/hunter_x_hunter/كورابيكا/image_3.webp',
    'assets/images/hunter_x_hunter/كوروتوبي/image_1.webp',
    'assets/images/hunter_x_hunter/كوروتوبي/image_2.webp',
    'assets/images/hunter_x_hunter/كوروتوبي/image_3.webp',
    'assets/images/hunter_x_hunter/كورولو/image_1.webp',
    'assets/images/hunter_x_hunter/كورولو/image_2.webp',
    'assets/images/hunter_x_hunter/كورولو/image_3.webp',
    'assets/images/hunter_x_hunter/كولت/image_1.webp',
    'assets/images/hunter_x_hunter/كولت/image_2.webp',
    'assets/images/hunter_x_hunter/كولت/image_3.webp',
    'assets/images/hunter_x_hunter/كوموغي/image_1.webp',
    'assets/images/hunter_x_hunter/كوموغي/image_2.webp',
    'assets/images/hunter_x_hunter/كوموغي/image_3.webp',
    'assets/images/hunter_x_hunter/كيكيو زولديك/image_1.webp',
    'assets/images/hunter_x_hunter/كيكيو زولديك/image_2.webp',
    'assets/images/hunter_x_hunter/كيكيو زولديك/image_3.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_1.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_2.webp',
    'assets/images/hunter_x_hunter/كيلوا/image_3.webp',
    'assets/images/hunter_x_hunter/لاتارزا/image_1.webp',
    'assets/images/hunter_x_hunter/لاتارزا/image_2.webp',
    'assets/images/hunter_x_hunter/لاتارزا/image_3.webp',
    'assets/images/hunter_x_hunter/لايت نوستراد/image_1.webp',
    'assets/images/hunter_x_hunter/لايت نوستراد/image_2.webp',
    'assets/images/hunter_x_hunter/لايت نوستراد/image_3.webp',
    'assets/images/hunter_x_hunter/ليبو/image_1.webp',
    'assets/images/hunter_x_hunter/ليبو/image_2.webp',
    'assets/images/hunter_x_hunter/ليبو/image_3.webp',
    'assets/images/hunter_x_hunter/ليوريو/image_1.webp',
    'assets/images/hunter_x_hunter/ليوريو/image_2.webp',
    'assets/images/hunter_x_hunter/ليوريو/image_3.webp',
    'assets/images/hunter_x_hunter/ليول/image_1.webp',
    'assets/images/hunter_x_hunter/ليول/image_2.webp',
    'assets/images/hunter_x_hunter/ليول/image_3.webp',
    'assets/images/hunter_x_hunter/ماتشي/image_1.webp',
    'assets/images/hunter_x_hunter/ماتشي/image_2.webp',
    'assets/images/hunter_x_hunter/ماتشي/image_3.webp',
    'assets/images/hunter_x_hunter/ملكة النمل/image_1.webp',
    'assets/images/hunter_x_hunter/ملكة النمل/image_2.webp',
    'assets/images/hunter_x_hunter/ملكة النمل/image_3.webp',
    'assets/images/hunter_x_hunter/ميتو/image_1.webp',
    'assets/images/hunter_x_hunter/ميتو/image_2.webp',
    'assets/images/hunter_x_hunter/ميتو/image_3.webp',
    'assets/images/hunter_x_hunter/ميرويم/image_1.webp',
    'assets/images/hunter_x_hunter/ميرويم/image_2.webp',
    'assets/images/hunter_x_hunter/ميرويم/image_3.webp',
    'assets/images/hunter_x_hunter/ميزايستومو (البقرة)/image_1.webp',
    'assets/images/hunter_x_hunter/ميزايستومو (البقرة)/image_2.webp',
    'assets/images/hunter_x_hunter/ميزايستومو (البقرة)/image_3.webp',
    'assets/images/hunter_x_hunter/ميلودي/image_1.webp',
    'assets/images/hunter_x_hunter/ميلودي/image_2.webp',
    'assets/images/hunter_x_hunter/ميلودي/image_3.webp',
    'assets/images/hunter_x_hunter/ميلوكي/image_1.webp',
    'assets/images/hunter_x_hunter/ميلوكي/image_2.webp',
    'assets/images/hunter_x_hunter/ميلوكي/image_3.webp',
    'assets/images/hunter_x_hunter/ميليورون/image_1.webp',
    'assets/images/hunter_x_hunter/ميليورون/image_2.webp',
    'assets/images/hunter_x_hunter/ميليورون/image_3.webp',
    'assets/images/hunter_x_hunter/مينشي/image_1.webp',
    'assets/images/hunter_x_hunter/مينشي/image_2.webp',
    'assets/images/hunter_x_hunter/مينشي/image_3.webp',
    'assets/images/hunter_x_hunter/ناكل/image_1.webp',
    'assets/images/hunter_x_hunter/ناكل/image_2.webp',
    'assets/images/hunter_x_hunter/ناكل/image_3.webp',
    'assets/images/hunter_x_hunter/نانيكا/image_1.webp',
    'assets/images/hunter_x_hunter/نانيكا/image_2.webp',
    'assets/images/hunter_x_hunter/نانيكا/image_3.webp',
    'assets/images/hunter_x_hunter/نوبوناغا/image_1.webp',
    'assets/images/hunter_x_hunter/نوبوناغا/image_2.webp',
    'assets/images/hunter_x_hunter/نوبوناغا/image_3.webp',
    'assets/images/hunter_x_hunter/نوف/image_1.webp',
    'assets/images/hunter_x_hunter/نوف/image_2.webp',
    'assets/images/hunter_x_hunter/نوف/image_3.webp',
    'assets/images/hunter_x_hunter/نيتيرو/image_1.webp',
    'assets/images/hunter_x_hunter/نيتيرو/image_2.webp',
    'assets/images/hunter_x_hunter/نيتيرو/image_3.webp',
    'assets/images/hunter_x_hunter/نيون نوستراد/image_1.webp',
    'assets/images/hunter_x_hunter/نيون نوستراد/image_2.webp',
    'assets/images/hunter_x_hunter/نيون نوستراد/image_3.webp',
    'assets/images/hunter_x_hunter/هارونا/image_1.webp',
    'assets/images/hunter_x_hunter/هارونا/image_2.webp',
    'assets/images/hunter_x_hunter/هارونا/image_3.webp',
    'assets/images/hunter_x_hunter/هانزو/image_1.webp',
    'assets/images/hunter_x_hunter/هانزو/image_2.webp',
    'assets/images/hunter_x_hunter/هانزو/image_3.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_1.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_2.webp',
    'assets/images/hunter_x_hunter/هيسوكا/image_3.webp',
    'assets/images/hunter_x_hunter/ويلفن/image_1.webp',
    'assets/images/hunter_x_hunter/ويلفن/image_2.webp',
    'assets/images/hunter_x_hunter/ويلفن/image_3.webp',
    'assets/images/hunter_x_hunter/وينغ/image_1.webp',
    'assets/images/hunter_x_hunter/وينغ/image_2.webp',
    'assets/images/hunter_x_hunter/وينغ/image_3.webp',
    'assets/images/hunter_x_hunter/يوبي/image_1.webp',
    'assets/images/hunter_x_hunter/يوبي/image_2.webp',
    'assets/images/hunter_x_hunter/يوبي/image_3.webp',
  ],
  'Black Clover': [
    'assets/images/black_clover/Acier Silva/image_1.webp',
    'assets/images/black_clover/Asta/image_1.webp',
    'assets/images/black_clover/Augustus Kira Clover XIII/image_1.webp',
    'assets/images/black_clover/Charlotte Roselei/image_1.webp',
    'assets/images/black_clover/Charmy Pappitson/image_1.webp',
    'assets/images/black_clover/Damnatio Kira/image_1.webp',
    'assets/images/black_clover/Dante Zogratis/image_1.webp',
    'assets/images/black_clover/Dorothy Unsworth/image_1.webp',
    'assets/images/black_clover/Fana/image_1.webp',
    'assets/images/black_clover/Finral Roulacase/image_1.webp',
    'assets/images/black_clover/Fuegoleon Vermillion/image_1.webp',
    'assets/images/black_clover/Gadjah/image_1.webp',
    'assets/images/black_clover/Gauche Adlai/image_1.webp',
    'assets/images/black_clover/Gifso/image_1.webp',
    'assets/images/black_clover/Gordon Agrippa/image_1.webp',
    'assets/images/black_clover/Grey/image_1.webp',
    'assets/images/black_clover/Gueldre Poizot/image_1.webp',
    'assets/images/black_clover/Henry Legolant/image_1.webp',
    'assets/images/black_clover/Jack the Ripper/image_1.webp',
    'assets/images/black_clover/Julius Novachrono/image_1.webp',
    'assets/images/black_clover/Kahono/image_1.webp',
    'assets/images/black_clover/Kaiser Granvorka/image_1.webp',
    'assets/images/black_clover/Kiato/image_1.webp',
    'assets/images/black_clover/Klaus Lunettes/image_1.webp',
    'assets/images/black_clover/Langris Vaude/image_1.webp',
    'assets/images/black_clover/Lemiel Silvamillion Clover/image_1.webp',
    'assets/images/black_clover/Leopold Vermillion/image_1.webp',
    'assets/images/black_clover/Liebe/image_1.webp',
    'assets/images/black_clover/Lily Aquaria/image_1.webp',
    'assets/images/black_clover/Lolopechka/image_1.webp',
    'assets/images/black_clover/Luck Voltia/image_1.webp',
    'assets/images/black_clover/Magna Swing/image_1.webp',
    'assets/images/black_clover/Marie Adlai/image_1.webp',
    'assets/images/black_clover/Mars/image_1.webp',
    'assets/images/black_clover/Marx Francois/image_1.webp',
    'assets/images/black_clover/Megicula/image_1.webp',
    'assets/images/black_clover/Mereoleona Vermillion/image_1.webp',
    'assets/images/black_clover/Mimosa Vermillion/image_1.webp',
    'assets/images/black_clover/Nacht Faust/image_1.webp',
    'assets/images/black_clover/Noelle Silva/image_1.webp',
    'assets/images/black_clover/Nozel Silva/image_1.webp',
    'assets/images/black_clover/Orsi Orfai/image_1.webp',
    'assets/images/black_clover/Owen/image_1.webp',
    'assets/images/black_clover/Patolli/image_1.webp',
    'assets/images/black_clover/Rades Spirito/image_1.webp',
    'assets/images/black_clover/Revchi Salik/image_1.webp',
    'assets/images/black_clover/Rhya/image_1.webp',
    'assets/images/black_clover/Richita/image_1.webp',
    'assets/images/black_clover/Rill Boismortier/image_1.webp',
    'assets/images/black_clover/Salamander/image_1.webp',
    'assets/images/black_clover/Sally/image_1.webp',
    'assets/images/black_clover/Secre Swallowtail/image_1.webp',
    'assets/images/black_clover/Sekke Bronzazza/image_1.webp',
    'assets/images/black_clover/Sol Marron/image_1.webp',
    'assets/images/black_clover/Solid Silva/image_1.webp',
    'assets/images/black_clover/Sylph/image_1.webp',
    'assets/images/black_clover/Undine/image_1.webp',
    'assets/images/black_clover/Vanessa Enoteca/image_1.webp',
    'assets/images/black_clover/Vanica Zogratis/image_1.webp',
    'assets/images/black_clover/Vetto/image_1.webp',
    'assets/images/black_clover/William Vangeance/image_1.webp',
    'assets/images/black_clover/Witch Queen/image_1.webp',
    'assets/images/black_clover/Yami Sukehiro/image_1.webp',
    'assets/images/black_clover/Yuno Grinberryall/image_1.webp',
    'assets/images/black_clover/Zagred/image_1.webp',
    'assets/images/black_clover/Zenon Zogratis/image_1.webp',
    'assets/images/black_clover/Zora Ideale/image_1.webp',
  ],
  'Demon Slayer': [
    'assets/images/demon_slayer/Akaza/image_1.webp',
    'assets/images/demon_slayer/Amane Ubuyashiki/image_1.webp',
    'assets/images/demon_slayer/Daki/image_1.webp',
    'assets/images/demon_slayer/Doma/image_1.webp',
    'assets/images/demon_slayer/Enmu/image_1.webp',
    'assets/images/demon_slayer/Genya Shinazugawa/image_1.webp',
    'assets/images/demon_slayer/Giyu Tomioka/image_1.webp',
    'assets/images/demon_slayer/Goto/image_1.webp',
    'assets/images/demon_slayer/Gyokko/image_1.webp',
    'assets/images/demon_slayer/Gyomei Himejima/image_1.webp',
    'assets/images/demon_slayer/Gyutaro/image_1.webp',
    'assets/images/demon_slayer/Hand Demon/image_1.webp',
    'assets/images/demon_slayer/Hantengu/image_1.webp',
    'assets/images/demon_slayer/Hotaru Haganezuka/image_1.webp',
    'assets/images/demon_slayer/Inosuke Hashibira/image_1.webp',
    'assets/images/demon_slayer/Kagaya Ubuyashiki/image_1.webp',
    'assets/images/demon_slayer/Kanao Tsuyuri/image_1.webp',
    'assets/images/demon_slayer/Kie Kamado/image_1.webp',
    'assets/images/demon_slayer/Kiyo Terauchi and Sumi Nakahara and Naho Takada/image_1.webp',
    'assets/images/demon_slayer/Kokushibo/image_1.webp',
    'assets/images/demon_slayer/Kotetsu/image_1.webp',
    'assets/images/demon_slayer/Kyogai/image_1.webp',
    'assets/images/demon_slayer/Kyojuro Rengoku/image_1.webp',
    'assets/images/demon_slayer/Mitsuri Kanroji/image_1.webp',
    'assets/images/demon_slayer/Muichiro Tokito/image_1.webp',
    'assets/images/demon_slayer/Muzan Kibutsuji/image_1.webp',
    'assets/images/demon_slayer/Nakime/image_1.webp',
    'assets/images/demon_slayer/Nezuko Kamado/image_1.webp',
    'assets/images/demon_slayer/Obanai Iguro/image_1.webp',
    'assets/images/demon_slayer/Rui/image_1.webp',
    'assets/images/demon_slayer/Sabito/image_1.webp',
    'assets/images/demon_slayer/Sakonji Urokodaki/image_1.webp',
    'assets/images/demon_slayer/Sanemi Shinazugawa/image_1.webp',
    'assets/images/demon_slayer/Shinobu Kocho/image_1.webp',
    'assets/images/demon_slayer/Susamaru/image_1.webp',
    'assets/images/demon_slayer/Tamayo/image_1.webp',
    'assets/images/demon_slayer/Tanjiro Kamado/image_1.webp',
    'assets/images/demon_slayer/Tanjuro Kamado/image_1.webp',
    'assets/images/demon_slayer/Tecchin Tecchikawahara/image_1.webp',
    'assets/images/demon_slayer/Tengen Uzui/image_1.webp',
    'assets/images/demon_slayer/Yoriichi/image_1.webp',
    'assets/images/demon_slayer/Yushiro/image_1.webp',
    'assets/images/demon_slayer/Zenitsu Agatsuma/image_1.webp',
  ],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
  'Jujutsu Kaisen': [],
  'My Hero Academia': [],
  'One Piece': [],
  'Solo Leveling': [],
  'Tokyo Revengers': [],
  'Vinland Saga': [],
};