const Map<String, List<String>> categoryAssets = {
  'Attack on Titan': [
    "assets/images/attack_on_titan/Annie LEONHART.webp",
    "assets/images/attack_on_titan/Armin ARLERT.webp",
    "assets/images/attack_on_titan/Bertholdt HOOVER.webp",
    "assets/images/attack_on_titan/Conny SPRINGER.webp",
    "assets/images/attack_on_titan/Dot PYXIS.webp",
    "assets/images/attack_on_titan/Eld GIN.webp",
    "assets/images/attack_on_titan/Eren YAEGER.webp",
    "assets/images/attack_on_titan/Erwin SMITH.webp",
    "assets/images/attack_on_titan/Gunther SCHULTZ.webp",
    "assets/images/attack_on_titan/Hange ZOE.webp",
    "assets/images/attack_on_titan/Hannes.webp",
    "assets/images/attack_on_titan/Jean KIRSCHTEIN.webp",
    "assets/images/attack_on_titan/Levi ACKERMAN.webp",
    "assets/images/attack_on_titan/Marco BODT.webp",
    "assets/images/attack_on_titan/Mikasa ACKERMAN.webp",
  ],
  'Black Clover': [
    "assets/images/black_clover/Acier Silva.webp",
    "assets/images/black_clover/Asta.webp",
    "assets/images/black_clover/Augustus Kira Clover XIII.webp",
    "assets/images/black_clover/Charlotte Roselei.webp",
    "assets/images/black_clover/Charmy Pappitson.webp",
    "assets/images/black_clover/Damnatio Kira.webp",
    "assets/images/black_clover/Dante Zogratis.webp",
    "assets/images/black_clover/Dorothy Unsworth.webp",
    "assets/images/black_clover/Fana.webp",
    "assets/images/black_clover/Finral Roulacase.webp",
    "assets/images/black_clover/Fuegoleon Vermillion.webp",
    "assets/images/black_clover/Gadjah.webp",
    "assets/images/black_clover/Gauche Adlai.webp",
    "assets/images/black_clover/Gifso.webp",
    "assets/images/black_clover/Gordon Agrippa.webp",
    "assets/images/black_clover/Grey.webp",
    "assets/images/black_clover/Gueldre Poizot.webp",
    "assets/images/black_clover/Henry Legolant.webp",
    "assets/images/black_clover/Jack the Ripper.webp",
    "assets/images/black_clover/Julius Novachrono.webp",
    "assets/images/black_clover/Kahono.webp",
    "assets/images/black_clover/Kaiser Granvorka.webp",
    "assets/images/black_clover/Kiato.webp",
    "assets/images/black_clover/Klaus Lunettes.webp",
    "assets/images/black_clover/Langris Vaude.webp",
    "assets/images/black_clover/Lemiel Silvamillion Clover.webp",
    "assets/images/black_clover/Leopold Vermillion.webp",
    "assets/images/black_clover/Liebe.webp",
    "assets/images/black_clover/Lily Aquaria.webp",
    "assets/images/black_clover/Lolopechka.webp",
    "assets/images/black_clover/Luck Voltia.webp",
    "assets/images/black_clover/Magna Swing.webp",
    "assets/images/black_clover/Marie Adlai.webp",
    "assets/images/black_clover/Mars.webp",
    "assets/images/black_clover/Marx Francois.webp",
    "assets/images/black_clover/Megicula.webp",
    "assets/images/black_clover/Mereoleona Vermillion.webp",
    "assets/images/black_clover/Mimosa Vermillion.webp",
    "assets/images/black_clover/Nacht Faust.webp",
    "assets/images/black_clover/Noelle Silva.webp",
    "assets/images/black_clover/Nozel Silva.webp",
    "assets/images/black_clover/Orsi Orfai.webp",
    "assets/images/black_clover/Owen.webp",
    "assets/images/black_clover/Patolli.webp",
    "assets/images/black_clover/Rades Spirito.webp",
    "assets/images/black_clover/Revchi Salik.webp",
    "assets/images/black_clover/Rhya.webp",
    "assets/images/black_clover/Richita.webp",
    "assets/images/black_clover/Rill Boismortier.webp",
    "assets/images/black_clover/Salamander.webp",
    "assets/images/black_clover/Sally.webp",
    "assets/images/black_clover/Secre Swallowtail.webp",
    "assets/images/black_clover/Sekke Bronzazza.webp",
    "assets/images/black_clover/Sol Marron.webp",
    "assets/images/black_clover/Solid Silva.webp",
    "assets/images/black_clover/Sylph.webp",
    "assets/images/black_clover/Undine.webp",
    "assets/images/black_clover/Vanessa Enoteca.webp",
    "assets/images/black_clover/Vanica Zogratis.webp",
    "assets/images/black_clover/Vetto.webp",
    "assets/images/black_clover/William Vangeance.webp",
    "assets/images/black_clover/Witch Queen.webp",
    "assets/images/black_clover/Yami Sukehiro.webp",
    "assets/images/black_clover/Yuno Grinberryall.webp",
    "assets/images/black_clover/Zagred.webp",
    "assets/images/black_clover/Zenon Zogratis.webp",
    "assets/images/black_clover/Zora Ideale.webp",
  ],
  'Demon Slayer': [
    "assets/images/demon_slayer/Akaza.webp",
    "assets/images/demon_slayer/Amane Ubuyashiki.webp",
    "assets/images/demon_slayer/Daki.webp",
    "assets/images/demon_slayer/Doma.webp",
    "assets/images/demon_slayer/Enmu.webp",
    "assets/images/demon_slayer/Genya Shinazugawa.webp",
    "assets/images/demon_slayer/Giyu Tomioka.webp",
    "assets/images/demon_slayer/Goto.webp",
    "assets/images/demon_slayer/Gyokko.webp",
    "assets/images/demon_slayer/Gyomei Himejima.webp",
    "assets/images/demon_slayer/Gyutaro.webp",
    "assets/images/demon_slayer/Hand Demon.webp",
    "assets/images/demon_slayer/Hantengu.webp",
    "assets/images/demon_slayer/Hotaru Haganezuka.webp",
    "assets/images/demon_slayer/Inosuke Hashibira.webp",
    "assets/images/demon_slayer/Kagaya Ubuyashiki.webp",
    "assets/images/demon_slayer/Kanao Tsuyuri.webp",
    "assets/images/demon_slayer/Kie Kamado.webp",
    "assets/images/demon_slayer/Kiyo Terauchi and Sumi Nakahara and Naho Takada.webp",
    "assets/images/demon_slayer/Kokushibo.webp",
    "assets/images/demon_slayer/Kotetsu.webp",
    "assets/images/demon_slayer/Kyogai.webp",
    "assets/images/demon_slayer/Kyojuro Rengoku.webp",
    "assets/images/demon_slayer/Mitsuri Kanroji.webp",
    "assets/images/demon_slayer/Muichiro Tokito.webp",
    "assets/images/demon_slayer/Muzan Kibutsuji.webp",
    "assets/images/demon_slayer/Nakime.webp",
    "assets/images/demon_slayer/Nezuko Kamado.webp",
    "assets/images/demon_slayer/Obanai Iguro.webp",
    "assets/images/demon_slayer/Rui.webp",
    "assets/images/demon_slayer/Sabito.webp",
    "assets/images/demon_slayer/Sakonji Urokodaki.webp",
    "assets/images/demon_slayer/Sanemi Shinazugawa.webp",
    "assets/images/demon_slayer/Shinobu Kocho.webp",
    "assets/images/demon_slayer/Susamaru.webp",
    "assets/images/demon_slayer/Tamayo.webp",
    "assets/images/demon_slayer/Tanjiro Kamado.webp",
    "assets/images/demon_slayer/Tanjuro Kamado.webp",
    "assets/images/demon_slayer/Tecchin Tecchikawahara.webp",
    "assets/images/demon_slayer/Tengen Uzui.webp",
    "assets/images/demon_slayer/Yoriichi.webp",
    "assets/images/demon_slayer/Yushiro.webp",
    "assets/images/demon_slayer/Zenitsu Agatsuma.webp",
  ],
  'Hunter X Hunter': [
    "assets/images/hunter_x_hunter/Abengane.webp",
    "assets/images/hunter_x_hunter/Alluka Zoldyck.webp",
    "assets/images/hunter_x_hunter/Amane.webp",
    "assets/images/hunter_x_hunter/Anita.webp",
    "assets/images/hunter_x_hunter/Baise.webp",
    "assets/images/hunter_x_hunter/Bara.webp",
    "assets/images/hunter_x_hunter/Basho.webp",
    "assets/images/hunter_x_hunter/Beans.webp",
    "assets/images/hunter_x_hunter/Binolt.webp",
    "assets/images/hunter_x_hunter/Biscuit Krueger.webp",
    "assets/images/hunter_x_hunter/Boki.webp",
    "assets/images/hunter_x_hunter/Bonolenov Ndongo.webp",
    "assets/images/hunter_x_hunter/Bopobo.webp",
    "assets/images/hunter_x_hunter/Botobai Gigante.webp",
    "assets/images/hunter_x_hunter/Bourbon.webp",
    "assets/images/hunter_x_hunter/Buhara.webp",
    "assets/images/hunter_x_hunter/Canary.webp",
    "assets/images/hunter_x_hunter/Captain.webp",
    "assets/images/hunter_x_hunter/Centipede.webp",
    "assets/images/hunter_x_hunter/Cheadle Yorkshire.webp",
    "assets/images/hunter_x_hunter/Cheetu.webp",
    "assets/images/hunter_x_hunter/Chimera Ant Queen.webp",
    "assets/images/hunter_x_hunter/Chrollo Lucilfer.webp",
    "assets/images/hunter_x_hunter/Cluck.webp",
    "assets/images/hunter_x_hunter/Cocco.webp",
    "assets/images/hunter_x_hunter/Colt.webp",
    "assets/images/hunter_x_hunter/Dalzollene.webp",
    "assets/images/hunter_x_hunter/Dwun.webp",
    "assets/images/hunter_x_hunter/eta and elena.webp",
    "assets/images/hunter_x_hunter/Feitan Portor.webp",
    "assets/images/hunter_x_hunter/Flutter.webp",
    "assets/images/hunter_x_hunter/Franklin Bordeau.webp",
    "assets/images/hunter_x_hunter/Gel.webp",
    "assets/images/hunter_x_hunter/Genthru.webp",
    "assets/images/hunter_x_hunter/Geretta.webp",
    "assets/images/hunter_x_hunter/Gido.webp",
    "assets/images/hunter_x_hunter/Ging Freecss.webp",
    "assets/images/hunter_x_hunter/Ginta.webp",
    "assets/images/hunter_x_hunter/Gon Freecss.webp",
    "assets/images/hunter_x_hunter/Goreinu.webp",
    "assets/images/hunter_x_hunter/Gotoh.webp",
    "assets/images/hunter_x_hunter/Grachan.webp",
    "assets/images/hunter_x_hunter/Gun-toting Ant.webp",
    "assets/images/hunter_x_hunter/Gyro.webp",
    "assets/images/hunter_x_hunter/Hanzo.webp",
    "assets/images/hunter_x_hunter/Haruna.webp",
    "assets/images/hunter_x_hunter/Heavens Arena.webp",
    "assets/images/hunter_x_hunter/Hina.webp",
    "assets/images/hunter_x_hunter/Hisoka Morow.webp",
    "assets/images/hunter_x_hunter/Ikalgo.webp",
    "assets/images/hunter_x_hunter/Illumi Zoldyck.webp",
    "assets/images/hunter_x_hunter/Isaac Netero.webp",
    "assets/images/hunter_x_hunter/Izunavi.webp",
    "assets/images/hunter_x_hunter/Johness.webp",
    "assets/images/hunter_x_hunter/Kaito the ant.webp",
    "assets/images/hunter_x_hunter/Kalluto Zoldyck.webp",
    "assets/images/hunter_x_hunter/Kanzai.webp",
    "assets/images/hunter_x_hunter/Kastro.webp",
    "assets/images/hunter_x_hunter/Kikyo Zoldyck.webp",
    "assets/images/hunter_x_hunter/Killua Zoldyck.webp",
    "assets/images/hunter_x_hunter/Kite.webp",
    "assets/images/hunter_x_hunter/Knov.webp",
    "assets/images/hunter_x_hunter/Knuckle Bine.webp",
    "assets/images/hunter_x_hunter/Komugi.webp",
    "assets/images/hunter_x_hunter/Kortopi.webp",
    "assets/images/hunter_x_hunter/Kurapika.webp",
    "assets/images/hunter_x_hunter/Kurt.webp",
    "assets/images/hunter_x_hunter/Leech.webp",
    "assets/images/hunter_x_hunter/Leol.webp",
    "assets/images/hunter_x_hunter/Leorio Paradinight.webp",
    "assets/images/hunter_x_hunter/Leroute.webp",
    "assets/images/hunter_x_hunter/Light Nostrade.webp",
    "assets/images/hunter_x_hunter/Lippo.webp",
    "assets/images/hunter_x_hunter/List.webp",
    "assets/images/hunter_x_hunter/Machi Komacine.webp",
    "assets/images/hunter_x_hunter/Maha Zoldyck.webp",
    "assets/images/hunter_x_hunter/Majtani.webp",
    "assets/images/hunter_x_hunter/Meleoron.webp",
    "assets/images/hunter_x_hunter/Melody.webp",
    "assets/images/hunter_x_hunter/Menchi.webp",
    "assets/images/hunter_x_hunter/Menthuthuyoupi.webp",
    "assets/images/hunter_x_hunter/Meruem.webp",
    "assets/images/hunter_x_hunter/Milluki Zoldyck.webp",
    "assets/images/hunter_x_hunter/Mito Freecss.webp",
    "assets/images/hunter_x_hunter/Mizaistom Nana.webp",
    "assets/images/hunter_x_hunter/Morel Mackernasey.webp",
    "assets/images/hunter_x_hunter/Mosquito.webp",
    "assets/images/hunter_x_hunter/Neferpitou.webp",
    "assets/images/hunter_x_hunter/Neon Nostrade.webp",
    "assets/images/hunter_x_hunter/Nobunaga Hazama.webp",
    "assets/images/hunter_x_hunter/Ortho.webp",
    "assets/images/hunter_x_hunter/Owl.webp",
    "assets/images/hunter_x_hunter/Pairo.webp",
    "assets/images/hunter_x_hunter/Pakunoda.webp",
    "assets/images/hunter_x_hunter/Palm Siberia.webp",
    "assets/images/hunter_x_hunter/Pariston Hill.webp",
    "assets/images/hunter_x_hunter/Phinks Magcub.webp",
    "assets/images/hunter_x_hunter/Pike.webp",
    "assets/images/hunter_x_hunter/Pokkle.webp",
    "assets/images/hunter_x_hunter/Ponzu.webp",
    "assets/images/hunter_x_hunter/Porcupine.webp",
    "assets/images/hunter_x_hunter/Pyon.webp",
    "assets/images/hunter_x_hunter/Quizzing Lady.webp",
    "assets/images/hunter_x_hunter/Rabid Dog.webp",
    "assets/images/hunter_x_hunter/Rammot.webp",
    "assets/images/hunter_x_hunter/Razor.webp",
    "assets/images/hunter_x_hunter/Reina.webp",
    "assets/images/hunter_x_hunter/Riehlvelt.webp",
    "assets/images/hunter_x_hunter/Saccho Kobayakawa.webp",
    "assets/images/hunter_x_hunter/Sadaso.webp",
    "assets/images/hunter_x_hunter/Saiyu.webp",
    "assets/images/hunter_x_hunter/Satotz.webp",
    "assets/images/hunter_x_hunter/Sedokan.webp",
    "assets/images/hunter_x_hunter/Shachmono Tocino.webp",
    "assets/images/hunter_x_hunter/Shaiapouf.webp",
    "assets/images/hunter_x_hunter/Shalnark.webp",
    "assets/images/hunter_x_hunter/Shidore.webp",
    "assets/images/hunter_x_hunter/Shizuku Murasaki.webp",
    "assets/images/hunter_x_hunter/Shoot McMahon.webp",
    "assets/images/hunter_x_hunter/Silva Zoldyck.webp",
    "assets/images/hunter_x_hunter/Squala.webp",
    "assets/images/hunter_x_hunter/sub.webp",
    "assets/images/hunter_x_hunter/Tonpa.webp",
    "assets/images/hunter_x_hunter/Tsezguerra.webp",
    "assets/images/hunter_x_hunter/Tsubone.webp",
    "assets/images/hunter_x_hunter/Uvogin.webp",
    "assets/images/hunter_x_hunter/Welfin.webp",
    "assets/images/hunter_x_hunter/Wing.webp",
    "assets/images/hunter_x_hunter/Worm.webp",
    "assets/images/hunter_x_hunter/Yunju.webp",
    "assets/images/hunter_x_hunter/Zazan.webp",
    "assets/images/hunter_x_hunter/Zeno Zoldyck.webp",
    "assets/images/hunter_x_hunter/Zepile.webp",
    "assets/images/hunter_x_hunter/Zigg Zoldyck.webp",
    "assets/images/hunter_x_hunter/Zushi.webp",
  ],
  'Naruto': [
    "assets/images/naruto/Akamaru.webp",
    "assets/images/naruto/Choji Akimichi.webp",
    "assets/images/naruto/Gaara.webp",
    "assets/images/naruto/Hinata Hyuga.webp",
    "assets/images/naruto/Hiruzen Sarutobi.webp",
    "assets/images/naruto/Ino Yamanaka.webp",
    "assets/images/naruto/Itachi Uchiha.webp",
    "assets/images/naruto/Jiraiya.webp",
    "assets/images/naruto/Kakashi Hatake.webp",
    "assets/images/naruto/Kiba Inuzuka.webp",
    "assets/images/naruto/Konohamaru Sarutobi.webp",
    "assets/images/naruto/Madara Uchiha.webp",
    "assets/images/naruto/Might Guy.webp",
    "assets/images/naruto/Minato Namikaze.webp",
    "assets/images/naruto/Naruto Uzumaki.webp",
    "assets/images/naruto/Neji Hyuga.webp",
    "assets/images/naruto/Obito Uchiha.webp",
    "assets/images/naruto/Orochimaru.webp",
    "assets/images/naruto/Rock Lee.webp",
    "assets/images/naruto/Sakura Haruno.webp",
    "assets/images/naruto/Sasuke Uchiha.webp",
    "assets/images/naruto/Shikamaru Nara.webp",
    "assets/images/naruto/Shizune.webp",
    "assets/images/naruto/Tsunade.webp",
  ],
  'One Piece': [
    "assets/images/one_piece/Abdullah.webp",
    "assets/images/one_piece/Absalom.webp",
    "assets/images/one_piece/Aisa.webp",
    "assets/images/one_piece/Albion.webp",
    "assets/images/one_piece/Alpacaman.webp",
    "assets/images/one_piece/Alvida.webp",
    "assets/images/one_piece/Aramaki.webp",
    "assets/images/one_piece/Arlong.webp",
    "assets/images/one_piece/Ashura Doji.webp",
    "assets/images/one_piece/Atlas.webp",
    "assets/images/one_piece/Atmos.webp",
    "assets/images/one_piece/Avalo Pizarro.webp",
    "assets/images/one_piece/Babanuki.webp",
    "assets/images/one_piece/Baby 5.webp",
    "assets/images/one_piece/Bacura.webp",
    "assets/images/one_piece/Banchina.webp",
    "assets/images/one_piece/Bao Huang.webp",
    "assets/images/one_piece/Bartholomew Kuma.webp",
    "assets/images/one_piece/Bartolomeo.webp",
    "assets/images/one_piece/Basil Hawkins.webp",
    "assets/images/one_piece/Bastille.webp",
    "assets/images/one_piece/Bell-m�re.webp",
    "assets/images/one_piece/Bellamy.webp",
    "assets/images/one_piece/Belo Betty.webp",
    "assets/images/one_piece/benn beckman.webp",
    "assets/images/one_piece/Bentham.webp",
    "assets/images/one_piece/Bepo.webp",
    "assets/images/one_piece/Black Maria.webp",
    "assets/images/one_piece/Blackback.webp",
    "assets/images/one_piece/Blenheim.webp",
    "assets/images/one_piece/Bluegilly.webp",
    "assets/images/one_piece/Blueno.webp",
    "assets/images/one_piece/Boa Hancock.webp",
    "assets/images/one_piece/Boa Marigold.webp",
    "assets/images/one_piece/Boa Sandersonia.webp",
    "assets/images/one_piece/Bobby Funk.webp",
    "assets/images/one_piece/Bogard.webp",
    "assets/images/one_piece/Bomba.webp",
    "assets/images/one_piece/Bonk Punch.webp",
    "assets/images/one_piece/Borsalino.webp",
    "assets/images/one_piece/Bourbon Jr..webp",
    "assets/images/one_piece/Brogy.webp",
    "assets/images/one_piece/Brook.webp",
    "assets/images/one_piece/Brutal Bull.webp",
    "assets/images/one_piece/Buchi.webp",
    "assets/images/one_piece/Buckingham Stussy.webp",
    "assets/images/one_piece/Buffalo.webp",
    "assets/images/one_piece/Buggy.webp",
    "assets/images/one_piece/Building Snake.webp",
    "assets/images/one_piece/Cabaji.webp",
    "assets/images/one_piece/Caesar Clown.webp",
    "assets/images/one_piece/Camie.webp",
    "assets/images/one_piece/Capone Bege.webp",
    "assets/images/one_piece/Capone Pez.webp",
    "assets/images/one_piece/Capote.webp",
    "assets/images/one_piece/Caribou.webp",
    "assets/images/one_piece/Carmel.webp",
    "assets/images/one_piece/Carrot.webp",
    "assets/images/one_piece/Catarina Devon.webp",
    "assets/images/one_piece/Cavendish.webp",
    "assets/images/one_piece/Cerberus.webp",
    "assets/images/one_piece/Charlos.webp",
    "assets/images/one_piece/Charlotte Amande.webp",
    "assets/images/one_piece/Charlotte Anana.webp",
    "assets/images/one_piece/Charlotte Br�l�e.webp",
    "assets/images/one_piece/Charlotte Chiffon.webp",
    "assets/images/one_piece/Charlotte Cracker.webp",
    "assets/images/one_piece/Charlotte Galette.webp",
    "assets/images/one_piece/Charlotte Katakuri.webp",
    "assets/images/one_piece/Charlotte Lola.webp",
    "assets/images/one_piece/Charlotte Mont-d'Or.webp",
    "assets/images/one_piece/Charlotte Moscato.webp",
    "assets/images/one_piece/Charlotte Nusstorte.webp",
    "assets/images/one_piece/Charlotte Opera.webp",
    "assets/images/one_piece/Charlotte Perospero.webp",
    "assets/images/one_piece/Charlotte Praline.webp",
    "assets/images/one_piece/Charlotte Pudding.webp",
    "assets/images/one_piece/Charlotte Smoothie.webp",
    "assets/images/one_piece/Charlotte Snack.webp",
    "assets/images/one_piece/Chess.webp",
    "assets/images/one_piece/Chew.webp",
    "assets/images/one_piece/Chimney.webp",
    "assets/images/one_piece/Chinjao.webp",
    "assets/images/one_piece/Choco Police.webp",
    "assets/images/one_piece/Chocolat.webp",
    "assets/images/one_piece/Chouchou.webp",
    "assets/images/one_piece/Cla�omh D. Clover.webp",
    "assets/images/one_piece/Cocoa.webp",
    "assets/images/one_piece/Conis.webp",
    "assets/images/one_piece/Coribou.webp",
    "assets/images/one_piece/Cosette.webp",
    "assets/images/one_piece/Cowboy.webp",
    "assets/images/one_piece/Crocodile.webp",
    "assets/images/one_piece/Crocus.webp",
    "assets/images/one_piece/Curly Dadan.webp",
    "assets/images/one_piece/Daifugo.webp",
    "assets/images/one_piece/Dalmatian.webp",
    "assets/images/one_piece/Dalton.webp",
    "assets/images/one_piece/Daruma.webp",
    "assets/images/one_piece/Daz Bonez.webp",
    "assets/images/one_piece/Decalvan Brother.webp",
    "assets/images/one_piece/Dellinger.webp",
    "assets/images/one_piece/Demalo Black.webp",
    "assets/images/one_piece/Denjiro.webp",
    "assets/images/one_piece/Diamante.webp",
    "assets/images/one_piece/Doberman.webp",
    "assets/images/one_piece/Doc Q.webp",
    "assets/images/one_piece/Doll.webp",
    "assets/images/one_piece/Doma.webp",
    "assets/images/one_piece/Domino.webp",
    "assets/images/one_piece/Donquixote Doflamingo.webp",
    "assets/images/one_piece/Donquixote Homing.webp",
    "assets/images/one_piece/Donquixote Mjosgard.webp",
    "assets/images/one_piece/Donquixote Rosinante.webp",
    "assets/images/one_piece/Dorry.webp",
    "assets/images/one_piece/Dracule Mihawk.webp",
    "assets/images/one_piece/Drip.webp",
    "assets/images/one_piece/Duval.webp",
    "assets/images/one_piece/Edison.webp",
    "assets/images/one_piece/Edward Newgate.webp",
    "assets/images/one_piece/Edward Weevil.webp",
    "assets/images/one_piece/Elizabello II.webp",
    "assets/images/one_piece/Emet.webp",
    "assets/images/one_piece/Emporio Ivankov.webp",
    "assets/images/one_piece/Enel.webp",
    "assets/images/one_piece/Ethanbaron V. Nusjuro.webp",
    "assets/images/one_piece/Eustass Kid.webp",
    "assets/images/one_piece/Fighting Bull.webp",
    "assets/images/one_piece/Fisher Tiger.webp",
    "assets/images/one_piece/Fossa.webp",
    "assets/images/one_piece/Foxy.webp",
    "assets/images/one_piece/Franky.webp",
    "assets/images/one_piece/Fukaboshi.webp",
    "assets/images/one_piece/Fukurokuju.webp",
    "assets/images/one_piece/Fukurou.webp",
    "assets/images/one_piece/Gaimon.webp",
    "assets/images/one_piece/Galdino.webp",
    "assets/images/one_piece/Gambia.webp",
    "assets/images/one_piece/Gan Fall.webp",
    "assets/images/one_piece/Gancho.webp",
    "assets/images/one_piece/Gatz.webp",
    "assets/images/one_piece/Gecko Moria.webp",
    "assets/images/one_piece/Gedatsu.webp",
    "assets/images/one_piece/Genbo.webp",
    "assets/images/one_piece/Genzo.webp",
    "assets/images/one_piece/Gin.webp",
    "assets/images/one_piece/Ginrummy.webp",
    "assets/images/one_piece/Gion.webp",
    "assets/images/one_piece/Gismonda.webp",
    "assets/images/one_piece/Gladius.webp",
    "assets/images/one_piece/Gloriosa.webp",
    "assets/images/one_piece/Going Merry.webp",
    "assets/images/one_piece/Goki.webp",
    "assets/images/one_piece/Gol D. Roger.webp",
    "assets/images/one_piece/Gonbe.webp",
    "assets/images/one_piece/Guernika.webp",
    "assets/images/one_piece/Hack (Fishmen).webp",
    "assets/images/one_piece/Hakugan.webp",
    "assets/images/one_piece/Hamburg.webp",
    "assets/images/one_piece/Hannyabal.webp",
    "assets/images/one_piece/Haredas.webp",
    "assets/images/one_piece/Hatchan.webp",
    "assets/images/one_piece/Hattori.webp",
    "assets/images/one_piece/Heat.webp",
    "assets/images/one_piece/Helmeppo.webp",
    "assets/images/one_piece/Hera.webp",
    "assets/images/one_piece/Heracles.webp",
    "assets/images/one_piece/Hibari.webp",
    "assets/images/one_piece/Higuma.webp",
    "assets/images/one_piece/Hikoichi.webp",
    "assets/images/one_piece/Hiluluk.webp",
    "assets/images/one_piece/Hina.webp",
    "assets/images/one_piece/Hiramera.webp",
    "assets/images/one_piece/Hogback.webp",
    "assets/images/one_piece/Hongo.webp",
    "assets/images/one_piece/Hyougoro.webp",
    "assets/images/one_piece/Hyouzou.webp",
    "assets/images/one_piece/Iceburg.webp",
    "assets/images/one_piece/Igaram.webp",
    "assets/images/one_piece/Ikkaku.webp",
    "assets/images/one_piece/Imu.webp",
    "assets/images/one_piece/Inazuma.webp",
    "assets/images/one_piece/Inuarashi.webp",
    "assets/images/one_piece/Ipponmatsu.webp",
    "assets/images/one_piece/Issho.webp",
    "assets/images/one_piece/Isuka.webp",
    "assets/images/one_piece/Itomimizu.webp",
    "assets/images/one_piece/Ivan X.webp",
    "assets/images/one_piece/Izou.webp",
    "assets/images/one_piece/Jabra.webp",
    "assets/images/one_piece/Jack.webp",
    "assets/images/one_piece/Jaguar D. Saul.webp",
    "assets/images/one_piece/Jaki.webp",
    "assets/images/one_piece/Jango.webp",
    "assets/images/one_piece/Jaygarcia Saturn.webp",
    "assets/images/one_piece/Jean Bart.webp",
    "assets/images/one_piece/Jeet.webp",
    "assets/images/one_piece/Jesus Burgess.webp",
    "assets/images/one_piece/Jewelry Bonney.webp",
    "assets/images/one_piece/Jimbei.webp",
    "assets/images/one_piece/John Giant.webp",
    "assets/images/one_piece/Johnny.webp",
    "assets/images/one_piece/Joseph.webp",
    "assets/images/one_piece/Joy Boy.webp",
    "assets/images/one_piece/Jozu.webp",
    "assets/images/one_piece/Kabu.webp",
    "assets/images/one_piece/Kaidou.webp",
    "assets/images/one_piece/Kaku.webp",
    "assets/images/one_piece/Kalgara.webp",
    "assets/images/one_piece/Kalifa.webp",
    "assets/images/one_piece/Kamakiri.webp",
    "assets/images/one_piece/Karoo.webp",
    "assets/images/one_piece/Kashii.webp",
    "assets/images/one_piece/Kawamatsu.webp",
    "assets/images/one_piece/Kaya.webp",
    "assets/images/one_piece/Kelly Funk.webp",
    "assets/images/one_piece/Kentauros.webp",
    "assets/images/one_piece/Kikunojo.webp",
    "assets/images/one_piece/Kikyo.webp",
    "assets/images/one_piece/Killer.webp",
    "assets/images/one_piece/Kin'emon.webp",
    "assets/images/one_piece/Kinderella.webp",
    "assets/images/one_piece/King.webp",
    "assets/images/one_piece/Kingbaum.webp",
    "assets/images/one_piece/Kiwi.webp",
    "assets/images/one_piece/Koby.webp",
    "assets/images/one_piece/Kokoro.webp",
    "assets/images/one_piece/Komachiyo.webp",
    "assets/images/one_piece/Kong.webp",
    "assets/images/one_piece/Kouzuki Hiyori.webp",
    "assets/images/one_piece/Kouzuki Momonosuke.webp",
    "assets/images/one_piece/Kouzuki Oden.webp",
    "assets/images/one_piece/Kouzuki Sukiyaki.webp",
    "assets/images/one_piece/Kouzuki Toki.webp",
    "assets/images/one_piece/Krieg.webp",
    "assets/images/one_piece/Kujaku.webp",
    "assets/images/one_piece/Kumadori.webp",
    "assets/images/one_piece/Kumashi.webp",
    "assets/images/one_piece/Kureha.webp",
    "assets/images/one_piece/Kuro.webp",
    "assets/images/one_piece/Kuroobi.webp",
    "assets/images/one_piece/Kurozumi Higurashi.webp",
    "assets/images/one_piece/Kurozumi Kanjuro.webp",
    "assets/images/one_piece/Kurozumi Orochi.webp",
    "assets/images/one_piece/Kurozumi Semimaru.webp",
    "assets/images/one_piece/Kurozumi Tama.webp",
    "assets/images/one_piece/Kuzan.webp",
    "assets/images/one_piece/Kyros.webp",
    "assets/images/one_piece/Laboon.webp",
    "assets/images/one_piece/Laffitte.webp",
    "assets/images/one_piece/Lao G.webp",
    "assets/images/one_piece/Leo.webp",
    "assets/images/one_piece/Lilith.webp",
    "assets/images/one_piece/Limejuice.webp",
    "assets/images/one_piece/Lindbergh.webp",
    "assets/images/one_piece/Lip Doughty.webp",
    "assets/images/one_piece/Little Oars Jr..webp",
    "assets/images/one_piece/Loki.webp",
    "assets/images/one_piece/Lord of the Coast.webp",
    "assets/images/one_piece/Lucky Roux.webp",
    "assets/images/one_piece/Machvise.webp",
    "assets/images/one_piece/Magellan.webp",
    "assets/images/one_piece/Maha.webp",
    "assets/images/one_piece/Makino.webp",
    "assets/images/one_piece/Manjaro.webp",
    "assets/images/one_piece/Mansherry.webp",
    "assets/images/one_piece/Marco.webp",
    "assets/images/one_piece/Marcus Mars.webp",
    "assets/images/one_piece/Marguerite.webp",
    "assets/images/one_piece/Marianne.webp",
    "assets/images/one_piece/Marshall D. Teach.webp",
    "assets/images/one_piece/Masked Deuce.webp",
    "assets/images/one_piece/Merry.webp",
    "assets/images/one_piece/Mikita.webp",
    "assets/images/one_piece/Minokoala.webp",
    "assets/images/one_piece/Minotaurus.webp",
    "assets/images/one_piece/Misery.webp",
    "assets/images/one_piece/Miss Father's Day.webp",
    "assets/images/one_piece/Miss Friday.webp",
    "assets/images/one_piece/Miss Monday.webp",
    "assets/images/one_piece/Miyagi.webp",
    "assets/images/one_piece/Mocha.webp",
    "assets/images/one_piece/Mohji.webp",
    "assets/images/one_piece/Momonga.webp",
    "assets/images/one_piece/Momoo.webp",
    "assets/images/one_piece/Monet.webp",
    "assets/images/one_piece/Monkey D. Dragon.webp",
    "assets/images/one_piece/Monkey D. Garp.webp",
    "assets/images/one_piece/Monkey D. Luffy.webp",
    "assets/images/one_piece/Mont Blanc Cricket.webp",
    "assets/images/one_piece/Mont Blanc Noland.webp",
    "assets/images/one_piece/Morgan.webp",
    "assets/images/one_piece/Morgans.webp",
    "assets/images/one_piece/Morley.webp",
    "assets/images/one_piece/Mororon.webp",
    "assets/images/one_piece/Mounblutain.webp",
    "assets/images/one_piece/Mousse.webp",
    "assets/images/one_piece/Mozu.webp",
    "assets/images/one_piece/Mr. 13.webp",
    "assets/images/one_piece/Mr. 5.webp",
    "assets/images/one_piece/Mr. 7.webp",
    "assets/images/one_piece/Nami.webp",
    "assets/images/one_piece/Namur.webp",
    "assets/images/one_piece/Napoleon.webp",
    "assets/images/one_piece/Nefertari D. Cobra.webp",
    "assets/images/one_piece/Nefertari D. Vivi.webp",
    "assets/images/one_piece/Nefertari Titi.webp",
    "assets/images/one_piece/Nekomamushi.webp",
    "assets/images/one_piece/Neptune.webp",
    "assets/images/one_piece/Nerine.webp",
    "assets/images/one_piece/Nico Olvia.webp",
    "assets/images/one_piece/Nico Robin.webp",
    "assets/images/one_piece/Nika (God).webp",
    "assets/images/one_piece/Nitro.webp",
    "assets/images/one_piece/Noble Croc.webp",
    "assets/images/one_piece/Nojiko.webp",
    "assets/images/one_piece/Nola.webp",
    "assets/images/one_piece/Nora Gitsune.webp",
    "assets/images/one_piece/Nyasha.webp",
    "assets/images/one_piece/Oars.webp",
    "assets/images/one_piece/Omasa.webp",
    "assets/images/one_piece/Onigumo.webp",
    "assets/images/one_piece/Orlumbus.webp",
    "assets/images/one_piece/Otohime.webp",
    "assets/images/one_piece/Pagaya.webp",
    "assets/images/one_piece/Page One.webp",
    "assets/images/one_piece/Pandaman.webp",
    "assets/images/one_piece/Pappag.webp",
    "assets/images/one_piece/patty.webp",
    "assets/images/one_piece/Paulie.webp",
    "assets/images/one_piece/Pedro.webp",
    "assets/images/one_piece/Pekoms.webp",
    "assets/images/one_piece/Pell.webp",
    "assets/images/one_piece/Penguin.webp",
    "assets/images/one_piece/Perona.webp",
    "assets/images/one_piece/Pica.webp",
    "assets/images/one_piece/Pickles.webp",
    "assets/images/one_piece/Porche.webp",
    "assets/images/one_piece/Portgas D. Ace.webp",
    "assets/images/one_piece/Portgas D. Rouge.webp",
    "assets/images/one_piece/Pound.webp",
    "assets/images/one_piece/Prince Grus.webp",
    "assets/images/one_piece/Prometheus.webp",
    "assets/images/one_piece/PX-5.webp",
    "assets/images/one_piece/Pythagoras.webp",
    "assets/images/one_piece/Queen Mama Chanter.webp",
    "assets/images/one_piece/Queen.webp",
    "assets/images/one_piece/Raijin.webp",
    "assets/images/one_piece/Raizo.webp",
    "assets/images/one_piece/Rakuyo.webp",
    "assets/images/one_piece/Rebecca.webp",
    "assets/images/one_piece/Rika.webp",
    "assets/images/one_piece/Riku Doldo III.webp",
    "assets/images/one_piece/Rob Lucci.webp",
    "assets/images/one_piece/Roddy.webp",
    "assets/images/one_piece/Roronoa Zoro.webp",
    "assets/images/one_piece/Rosward.webp",
    "assets/images/one_piece/Ryuboshi.webp",
    "assets/images/one_piece/S-Bear.webp",
    "assets/images/one_piece/S-Hawk.webp",
    "assets/images/one_piece/S-Shark.webp",
    "assets/images/one_piece/S-Snake.webp",
    "assets/images/one_piece/Sabo.webp",
    "assets/images/one_piece/Sadi.webp",
    "assets/images/one_piece/Sai.webp",
    "assets/images/one_piece/Sakazuki.webp",
    "assets/images/one_piece/Salome.webp",
    "assets/images/one_piece/Sanjuan Wolf.webp",
    "assets/images/one_piece/Sarahebi.webp",
    "assets/images/one_piece/Sarquiss.webp",
    "assets/images/one_piece/Sasaki.webp",
    "assets/images/one_piece/Scarlett.webp",
    "assets/images/one_piece/Scopper Gaban.webp",
    "assets/images/one_piece/Scratchmen Apoo.webp",
    "assets/images/one_piece/Sengoku.webp",
    "assets/images/one_piece/Senor Pink.webp",
    "assets/images/one_piece/Sentomaru.webp",
    "assets/images/one_piece/Shachi.webp",
    "assets/images/one_piece/Shaka.webp",
    "assets/images/one_piece/Shakuyaku.webp",
    "assets/images/one_piece/Shalria.webp",
    "assets/images/one_piece/Shanks.webp",
    "assets/images/one_piece/Sharinguru.webp",
    "assets/images/one_piece/Shepherd Ju Peter.webp",
    "assets/images/one_piece/Shiki.webp",
    "assets/images/one_piece/Shimotsuki Koushirou.webp",
    "assets/images/one_piece/Shimotsuki Kuina.webp",
    "assets/images/one_piece/Shimotsuki Ryuma.webp",
    "assets/images/one_piece/Shimotsuki Yasuie.webp",
    "assets/images/one_piece/Shinobu.webp",
    "assets/images/one_piece/Shirahoshi.webp",
    "assets/images/one_piece/Shirley.webp",
    "assets/images/one_piece/Shiryu.webp",
    "assets/images/one_piece/Shishilian.webp",
    "assets/images/one_piece/Shu.webp",
    "assets/images/one_piece/Shura.webp",
    "assets/images/one_piece/Silvers Rayleigh.webp",
    "assets/images/one_piece/Smiley.webp",
    "assets/images/one_piece/Smoker.webp",
    "assets/images/one_piece/Sodom and Gomorrah.webp",
    "assets/images/one_piece/Spandam.webp",
    "assets/images/one_piece/Speed.webp",
    "assets/images/one_piece/Stansen.webp",
    "assets/images/one_piece/Stomp.webp",
    "assets/images/one_piece/Streusen.webp",
    "assets/images/one_piece/Stussy.webp",
    "assets/images/one_piece/Sugar.webp",
    "assets/images/one_piece/Surume.webp",
    "assets/images/one_piece/Sweet Pea.webp",
    "assets/images/one_piece/T Bone.webp",
    "assets/images/one_piece/Tamago.webp",
    "assets/images/one_piece/Tashigi.webp",
    "assets/images/one_piece/Terracotta.webp",
    "assets/images/one_piece/Thatch.webp",
    "assets/images/one_piece/Thousand Sunny.webp",
    "assets/images/one_piece/Toko.webp",
    "assets/images/one_piece/Tom.webp",
    "assets/images/one_piece/Tony Tony Chopper.webp",
    "assets/images/one_piece/Topman Warcury.webp",
    "assets/images/one_piece/Trafalgar D Water Law.webp",
    "assets/images/one_piece/Trafalgar D. Water Lami.webp",
    "assets/images/one_piece/Trebol.webp",
    "assets/images/one_piece/Tristan.webp",
    "assets/images/one_piece/Tsunagoro.webp",
    "assets/images/one_piece/Tsuru.webp",
    "assets/images/one_piece/Tsurujo.webp",
    "assets/images/one_piece/Turco.webp",
    "assets/images/one_piece/Tyrannosaurus.webp",
    "assets/images/one_piece/Ulti.webp",
    "assets/images/one_piece/Urouge.webp",
    "assets/images/one_piece/Usopp.webp",
    "assets/images/one_piece/Uta.webp",
    "assets/images/one_piece/Van Augur.webp",
    "assets/images/one_piece/Vander Decken IX.webp",
    "assets/images/one_piece/Vasco Shot.webp",
    "assets/images/one_piece/Vegaforce-01.webp",
    "assets/images/one_piece/Vergo.webp",
    "assets/images/one_piece/Victoria Cindry.webp",
    "assets/images/one_piece/Vinsmoke Ichiji.webp",
    "assets/images/one_piece/Vinsmoke Judge.webp",
    "assets/images/one_piece/Vinsmoke Niji.webp",
    "assets/images/one_piece/Vinsmoke Reiju.webp",
    "assets/images/one_piece/Vinsmoke Sanji.webp",
    "assets/images/one_piece/Vinsmoke Sora.webp",
    "assets/images/one_piece/Vinsmoke Yonji.webp",
    "assets/images/one_piece/Viola.webp",
    "assets/images/one_piece/Vista.webp",
    "assets/images/one_piece/Vito.webp",
    "assets/images/one_piece/Wadatsumi.webp",
    "assets/images/one_piece/Wanda.webp",
    "assets/images/one_piece/Wanze.webp",
    "assets/images/one_piece/Wapol.webp",
    "assets/images/one_piece/Who's-Who.webp",
    "assets/images/one_piece/Wicca.webp",
    "assets/images/one_piece/Wire.webp",
    "assets/images/one_piece/Woop Slap.webp",
    "assets/images/one_piece/Wyper.webp",
    "assets/images/one_piece/X Drake.webp",
    "assets/images/one_piece/Yamato.webp",
    "assets/images/one_piece/yassopp.webp",
    "assets/images/one_piece/Yokozuna.webp",
    "assets/images/one_piece/York.webp",
    "assets/images/one_piece/Yosaku.webp",
    "assets/images/one_piece/Zeff.webp",
    "assets/images/one_piece/Zeus.webp",
    "assets/images/one_piece/Zunesha.webp",
  ],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
  'Jujutsu Kaisen': [],
  'My Hero Academia': [],
  'Solo Leveling': [],
  'Tokyo Revengers': [],
  'Vinland Saga': [],
};
