const Map<String, List<String>> categoryAssets = {
  'Attack on Titan': [ 
    "asset/images/attack_on_titan/Annie LEONHART.webp", 
    "asset/images/attack_on_titan/Armin ARLERT.webp", 
    "asset/images/attack_on_titan/Bertholdt HOOVER.webp", 
    "asset/images/attack_on_titan/Conny SPRINGER.webp", 
    "asset/images/attack_on_titan/Dot PYXIS.webp", 
    "asset/images/attack_on_titan/Eld GIN.webp", 
    "asset/images/attack_on_titan/Eren YAEGER.webp", 
    "asset/images/attack_on_titan/Erwin SMITH.webp", 
    "asset/images/attack_on_titan/Gunther SCHULTZ.webp", 
    "asset/images/attack_on_titan/Hange ZOE.webp", 
    "asset/images/attack_on_titan/Hannes.webp", 
    "asset/images/attack_on_titan/Jean KIRSCHTEIN.webp", 
    "asset/images/attack_on_titan/Levi ACKERMAN.webp", 
    "asset/images/attack_on_titan/Marco BODT.webp", 
    "asset/images/attack_on_titan/Mikasa ACKERMAN.webp", 
  ], 
  'Black Clover': [ 
    "asset/images/black_clover/Acier Silva.webp", 
    "asset/images/black_clover/Asta.webp", 
    "asset/images/black_clover/Augustus Kira Clover XIII.webp", 
    "asset/images/black_clover/Charlotte Roselei.webp", 
    "asset/images/black_clover/Charmy Pappitson.webp", 
    "asset/images/black_clover/Damnatio Kira.webp", 
    "asset/images/black_clover/Dante Zogratis.webp", 
    "asset/images/black_clover/Dorothy Unsworth.webp", 
    "asset/images/black_clover/Fana.webp", 
    "asset/images/black_clover/Finral Roulacase.webp", 
    "asset/images/black_clover/Fuegoleon Vermillion.webp", 
    "asset/images/black_clover/Gadjah.webp", 
    "asset/images/black_clover/Gauche Adlai.webp", 
    "asset/images/black_clover/Gifso.webp", 
    "asset/images/black_clover/Gordon Agrippa.webp", 
    "asset/images/black_clover/Grey.webp", 
    "asset/images/black_clover/Gueldre Poizot.webp", 
    "asset/images/black_clover/Henry Legolant.webp", 
    "asset/images/black_clover/Jack the Ripper.webp", 
    "asset/images/black_clover/Julius Novachrono.webp", 
    "asset/images/black_clover/Kahono.webp", 
    "asset/images/black_clover/Kaiser Granvorka.webp", 
    "asset/images/black_clover/Kiato.webp", 
    "asset/images/black_clover/Klaus Lunettes.webp", 
    "asset/images/black_clover/Langris Vaude.webp", 
    "asset/images/black_clover/Lemiel Silvamillion Clover.webp", 
    "asset/images/black_clover/Leopold Vermillion.webp", 
    "asset/images/black_clover/Liebe.webp", 
    "asset/images/black_clover/Lily Aquaria.webp", 
    "asset/images/black_clover/Lolopechka.webp", 
    "asset/images/black_clover/Luck Voltia.webp", 
    "asset/images/black_clover/Magna Swing.webp", 
    "asset/images/black_clover/Marie Adlai.webp", 
    "asset/images/black_clover/Mars.webp", 
    "asset/images/black_clover/Marx Francois.webp", 
    "asset/images/black_clover/Megicula.webp", 
    "asset/images/black_clover/Mereoleona Vermillion.webp", 
    "asset/images/black_clover/Mimosa Vermillion.webp", 
    "asset/images/black_clover/Nacht Faust.webp", 
    "asset/images/black_clover/Noelle Silva.webp", 
    "asset/images/black_clover/Nozel Silva.webp", 
    "asset/images/black_clover/Orsi Orfai.webp", 
    "asset/images/black_clover/Owen.webp", 
    "asset/images/black_clover/Patolli.webp", 
    "asset/images/black_clover/Rades Spirito.webp", 
    "asset/images/black_clover/Revchi Salik.webp", 
    "asset/images/black_clover/Rhya.webp", 
    "asset/images/black_clover/Richita.webp", 
    "asset/images/black_clover/Rill Boismortier.webp", 
    "asset/images/black_clover/Salamander.webp", 
    "asset/images/black_clover/Sally.webp", 
    "asset/images/black_clover/Secre Swallowtail.webp", 
    "asset/images/black_clover/Sekke Bronzazza.webp", 
    "asset/images/black_clover/Sol Marron.webp", 
    "asset/images/black_clover/Solid Silva.webp", 
    "asset/images/black_clover/Sylph.webp", 
    "asset/images/black_clover/Undine.webp", 
    "asset/images/black_clover/Vanessa Enoteca.webp", 
    "asset/images/black_clover/Vanica Zogratis.webp", 
    "asset/images/black_clover/Vetto.webp", 
    "asset/images/black_clover/William Vangeance.webp", 
    "asset/images/black_clover/Witch Queen.webp", 
    "asset/images/black_clover/Yami Sukehiro.webp", 
    "asset/images/black_clover/Yuno Grinberryall.webp", 
    "asset/images/black_clover/Zagred.webp", 
    "asset/images/black_clover/Zenon Zogratis.webp", 
    "asset/images/black_clover/Zora Ideale.webp", 
  ], 
  'Demon Slayer': [ 
    "asset/images/demon_slayer/Akaza.webp", 
    "asset/images/demon_slayer/Amane Ubuyashiki.webp", 
    "asset/images/demon_slayer/Daki.webp", 
    "asset/images/demon_slayer/Doma.webp", 
    "asset/images/demon_slayer/Enmu.webp", 
    "asset/images/demon_slayer/Genya Shinazugawa.webp", 
    "asset/images/demon_slayer/Giyu Tomioka.webp", 
    "asset/images/demon_slayer/Goto.webp", 
    "asset/images/demon_slayer/Gyokko.webp", 
    "asset/images/demon_slayer/Gyomei Himejima.webp", 
    "asset/images/demon_slayer/Gyutaro.webp", 
    "asset/images/demon_slayer/Hand Demon.webp", 
    "asset/images/demon_slayer/Hantengu.webp", 
    "asset/images/demon_slayer/Hotaru Haganezuka.webp", 
    "asset/images/demon_slayer/Inosuke Hashibira.webp", 
    "asset/images/demon_slayer/Kagaya Ubuyashiki.webp", 
    "asset/images/demon_slayer/Kanao Tsuyuri.webp", 
    "asset/images/demon_slayer/Kie Kamado.webp", 
    "asset/images/demon_slayer/Kiyo Terauchi and Sumi Nakahara and Naho Takada.webp", 
    "asset/images/demon_slayer/Kokushibo.webp", 
    "asset/images/demon_slayer/Kotetsu.webp", 
    "asset/images/demon_slayer/Kyogai.webp", 
    "asset/images/demon_slayer/Kyojuro Rengoku.webp", 
    "asset/images/demon_slayer/Mitsuri Kanroji.webp", 
    "asset/images/demon_slayer/Muichiro Tokito.webp", 
    "asset/images/demon_slayer/Muzan Kibutsuji.webp", 
    "asset/images/demon_slayer/Nakime.webp", 
    "asset/images/demon_slayer/Nezuko Kamado.webp", 
    "asset/images/demon_slayer/Obanai Iguro.webp", 
    "asset/images/demon_slayer/Rui.webp", 
    "asset/images/demon_slayer/Sabito.webp", 
    "asset/images/demon_slayer/Sakonji Urokodaki.webp", 
    "asset/images/demon_slayer/Sanemi Shinazugawa.webp", 
    "asset/images/demon_slayer/Shinobu Kocho.webp", 
    "asset/images/demon_slayer/Susamaru.webp", 
    "asset/images/demon_slayer/Tamayo.webp", 
    "asset/images/demon_slayer/Tanjiro Kamado.webp", 
    "asset/images/demon_slayer/Tanjuro Kamado.webp", 
    "asset/images/demon_slayer/Tecchin Tecchikawahara.webp", 
    "asset/images/demon_slayer/Tengen Uzui.webp", 
    "asset/images/demon_slayer/Yoriichi.webp", 
    "asset/images/demon_slayer/Yushiro.webp", 
    "asset/images/demon_slayer/Zenitsu Agatsuma.webp", 
  ], 
  'Hunter X Hunter': [ 
    "asset/images/hunter_x_hunter/Abengane.webp", 
    "asset/images/hunter_x_hunter/Alluka Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Amane.webp", 
    "asset/images/hunter_x_hunter/Anita.webp", 
    "asset/images/hunter_x_hunter/Baise.webp", 
    "asset/images/hunter_x_hunter/Bara.webp", 
    "asset/images/hunter_x_hunter/Basho.webp", 
    "asset/images/hunter_x_hunter/Beans.webp", 
    "asset/images/hunter_x_hunter/Binolt.webp", 
    "asset/images/hunter_x_hunter/Biscuit Krueger.webp", 
    "asset/images/hunter_x_hunter/Boki.webp", 
    "asset/images/hunter_x_hunter/Bonolenov Ndongo.webp", 
    "asset/images/hunter_x_hunter/Bopobo.webp", 
    "asset/images/hunter_x_hunter/Botobai Gigante.webp", 
    "asset/images/hunter_x_hunter/Bourbon.webp", 
    "asset/images/hunter_x_hunter/Buhara.webp", 
    "asset/images/hunter_x_hunter/Canary.webp", 
    "asset/images/hunter_x_hunter/Captain.webp", 
    "asset/images/hunter_x_hunter/Centipede.webp", 
    "asset/images/hunter_x_hunter/Cheadle Yorkshire.webp", 
    "asset/images/hunter_x_hunter/Cheetu.webp", 
    "asset/images/hunter_x_hunter/Chimera Ant Queen.webp", 
    "asset/images/hunter_x_hunter/Chrollo Lucilfer.webp", 
    "asset/images/hunter_x_hunter/Cluck.webp", 
    "asset/images/hunter_x_hunter/Cocco.webp", 
    "asset/images/hunter_x_hunter/Colt.webp", 
    "asset/images/hunter_x_hunter/Dalzollene.webp", 
    "asset/images/hunter_x_hunter/Dwun.webp", 
    "asset/images/hunter_x_hunter/eta and elena.webp", 
    "asset/images/hunter_x_hunter/Feitan Portor.webp", 
    "asset/images/hunter_x_hunter/Flutter.webp", 
    "asset/images/hunter_x_hunter/Franklin Bordeau.webp", 
    "asset/images/hunter_x_hunter/Gel.webp", 
    "asset/images/hunter_x_hunter/Genthru.webp", 
    "asset/images/hunter_x_hunter/Geretta.webp", 
    "asset/images/hunter_x_hunter/Gido.webp", 
    "asset/images/hunter_x_hunter/Ging Freecss.webp", 
    "asset/images/hunter_x_hunter/Ginta.webp", 
    "asset/images/hunter_x_hunter/Gon Freecss.webp", 
    "asset/images/hunter_x_hunter/Goreinu.webp", 
    "asset/images/hunter_x_hunter/Gotoh.webp", 
    "asset/images/hunter_x_hunter/Grachan.webp", 
    "asset/images/hunter_x_hunter/Gun-toting Ant.webp", 
    "asset/images/hunter_x_hunter/Gyro.webp", 
    "asset/images/hunter_x_hunter/Hanzo.webp", 
    "asset/images/hunter_x_hunter/Haruna.webp", 
    "asset/images/hunter_x_hunter/Heavens Arena.webp", 
    "asset/images/hunter_x_hunter/Hina.webp", 
    "asset/images/hunter_x_hunter/Hisoka Morow.webp", 
    "asset/images/hunter_x_hunter/Ikalgo.webp", 
    "asset/images/hunter_x_hunter/Illumi Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Isaac Netero.webp", 
    "asset/images/hunter_x_hunter/Izunavi.webp", 
    "asset/images/hunter_x_hunter/Johness.webp", 
    "asset/images/hunter_x_hunter/Kaito the ant.webp", 
    "asset/images/hunter_x_hunter/Kalluto Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Kanzai.webp", 
    "asset/images/hunter_x_hunter/Kastro.webp", 
    "asset/images/hunter_x_hunter/Kikyo Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Killua Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Kite.webp", 
    "asset/images/hunter_x_hunter/Knov.webp", 
    "asset/images/hunter_x_hunter/Knuckle Bine.webp", 
    "asset/images/hunter_x_hunter/Komugi.webp", 
    "asset/images/hunter_x_hunter/Kortopi.webp", 
    "asset/images/hunter_x_hunter/Kurapika.webp", 
    "asset/images/hunter_x_hunter/Kurt.webp", 
    "asset/images/hunter_x_hunter/Leech.webp", 
    "asset/images/hunter_x_hunter/Leol.webp", 
    "asset/images/hunter_x_hunter/Leorio Paradinight.webp", 
    "asset/images/hunter_x_hunter/Leroute.webp", 
    "asset/images/hunter_x_hunter/Light Nostrade.webp", 
    "asset/images/hunter_x_hunter/Lippo.webp", 
    "asset/images/hunter_x_hunter/List.webp", 
    "asset/images/hunter_x_hunter/Machi Komacine.webp", 
    "asset/images/hunter_x_hunter/Maha Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Majtani.webp", 
    "asset/images/hunter_x_hunter/Meleoron.webp", 
    "asset/images/hunter_x_hunter/Melody.webp", 
    "asset/images/hunter_x_hunter/Menchi.webp", 
    "asset/images/hunter_x_hunter/Menthuthuyoupi.webp", 
    "asset/images/hunter_x_hunter/Meruem.webp", 
    "asset/images/hunter_x_hunter/Milluki Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Mito Freecss.webp", 
    "asset/images/hunter_x_hunter/Mizaistom Nana.webp", 
    "asset/images/hunter_x_hunter/Morel Mackernasey.webp", 
    "asset/images/hunter_x_hunter/Mosquito.webp", 
    "asset/images/hunter_x_hunter/Neferpitou.webp", 
    "asset/images/hunter_x_hunter/Neon Nostrade.webp", 
    "asset/images/hunter_x_hunter/Nobunaga Hazama.webp", 
    "asset/images/hunter_x_hunter/Ortho.webp", 
    "asset/images/hunter_x_hunter/Owl.webp", 
    "asset/images/hunter_x_hunter/Pairo.webp", 
    "asset/images/hunter_x_hunter/Pakunoda.webp", 
    "asset/images/hunter_x_hunter/Palm Siberia.webp", 
    "asset/images/hunter_x_hunter/Pariston Hill.webp", 
    "asset/images/hunter_x_hunter/Phinks Magcub.webp", 
    "asset/images/hunter_x_hunter/Pike.webp", 
    "asset/images/hunter_x_hunter/Pokkle.webp", 
    "asset/images/hunter_x_hunter/Ponzu.webp", 
    "asset/images/hunter_x_hunter/Porcupine.webp", 
    "asset/images/hunter_x_hunter/Pyon.webp", 
    "asset/images/hunter_x_hunter/Quizzing Lady.webp", 
    "asset/images/hunter_x_hunter/Rabid Dog.webp", 
    "asset/images/hunter_x_hunter/Rammot.webp", 
    "asset/images/hunter_x_hunter/Razor.webp", 
    "asset/images/hunter_x_hunter/Reina.webp", 
    "asset/images/hunter_x_hunter/Riehlvelt.webp", 
    "asset/images/hunter_x_hunter/Saccho Kobayakawa.webp", 
    "asset/images/hunter_x_hunter/Sadaso.webp", 
    "asset/images/hunter_x_hunter/Saiyu.webp", 
    "asset/images/hunter_x_hunter/Satotz.webp", 
    "asset/images/hunter_x_hunter/Sedokan.webp", 
    "asset/images/hunter_x_hunter/Shachmono Tocino.webp", 
    "asset/images/hunter_x_hunter/Shaiapouf.webp", 
    "asset/images/hunter_x_hunter/Shalnark.webp", 
    "asset/images/hunter_x_hunter/Shidore.webp", 
    "asset/images/hunter_x_hunter/Shizuku Murasaki.webp", 
    "asset/images/hunter_x_hunter/Shoot McMahon.webp", 
    "asset/images/hunter_x_hunter/Silva Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Squala.webp", 
    "asset/images/hunter_x_hunter/sub.webp", 
    "asset/images/hunter_x_hunter/Tonpa.webp", 
    "asset/images/hunter_x_hunter/Tsezguerra.webp", 
    "asset/images/hunter_x_hunter/Tsubone.webp", 
    "asset/images/hunter_x_hunter/Uvogin.webp", 
    "asset/images/hunter_x_hunter/Welfin.webp", 
    "asset/images/hunter_x_hunter/Wing.webp", 
    "asset/images/hunter_x_hunter/Worm.webp", 
    "asset/images/hunter_x_hunter/Yunju.webp", 
    "asset/images/hunter_x_hunter/Zazan.webp", 
    "asset/images/hunter_x_hunter/Zeno Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Zepile.webp", 
    "asset/images/hunter_x_hunter/Zigg Zoldyck.webp", 
    "asset/images/hunter_x_hunter/Zushi.webp", 
  ], 
  'Naruto': [ 
    "asset/images/naruto/Akamaru.webp", 
    "asset/images/naruto/Choji Akimichi.webp", 
    "asset/images/naruto/Gaara.webp", 
    "asset/images/naruto/Hinata Hyuga.webp", 
    "asset/images/naruto/Hiruzen Sarutobi.webp", 
    "asset/images/naruto/Ino Yamanaka.webp", 
    "asset/images/naruto/Itachi Uchiha.webp", 
    "asset/images/naruto/Jiraiya.webp", 
    "asset/images/naruto/Kakashi Hatake.webp", 
    "asset/images/naruto/Kiba Inuzuka.webp", 
    "asset/images/naruto/Konohamaru Sarutobi.webp", 
    "asset/images/naruto/Madara Uchiha.webp", 
    "asset/images/naruto/Might Guy.webp", 
    "asset/images/naruto/Minato Namikaze.webp", 
    "asset/images/naruto/Naruto Uzumaki.webp", 
    "asset/images/naruto/Neji Hyuga.webp", 
    "asset/images/naruto/Obito Uchiha.webp", 
    "asset/images/naruto/Orochimaru.webp", 
    "asset/images/naruto/Rock Lee.webp", 
    "asset/images/naruto/Sakura Haruno.webp", 
    "asset/images/naruto/Sasuke Uchiha.webp", 
    "asset/images/naruto/Shikamaru Nara.webp", 
    "asset/images/naruto/Shizune.webp", 
    "asset/images/naruto/Tsunade.webp", 
  ], 
  'One Piece': [ 
    "asset/images/one_piece/Abdullah.webp", 
    "asset/images/one_piece/Absalom.webp", 
    "asset/images/one_piece/Aisa.webp", 
    "asset/images/one_piece/Albion.webp", 
    "asset/images/one_piece/Alpacaman.webp", 
    "asset/images/one_piece/Alvida.webp", 
    "asset/images/one_piece/Aramaki.webp", 
    "asset/images/one_piece/Arlong.webp", 
    "asset/images/one_piece/Ashura Doji.webp", 
    "asset/images/one_piece/Atlas.webp", 
    "asset/images/one_piece/Atmos.webp", 
    "asset/images/one_piece/Avalo Pizarro.webp", 
    "asset/images/one_piece/Babanuki.webp", 
    "asset/images/one_piece/Baby 5.webp", 
    "asset/images/one_piece/Bacura.webp", 
    "asset/images/one_piece/Banchina.webp", 
    "asset/images/one_piece/Bao Huang.webp", 
    "asset/images/one_piece/Bartholomew Kuma.webp", 
    "asset/images/one_piece/Bartolomeo.webp", 
    "asset/images/one_piece/Basil Hawkins.webp", 
    "asset/images/one_piece/Bastille.webp", 
    "asset/images/one_piece/Bell-m�re.webp", 
    "asset/images/one_piece/Bellamy.webp", 
    "asset/images/one_piece/Belo Betty.webp", 
    "asset/images/one_piece/benn beckman.webp", 
    "asset/images/one_piece/Bentham.webp", 
    "asset/images/one_piece/Bepo.webp", 
    "asset/images/one_piece/Black Maria.webp", 
    "asset/images/one_piece/Blackback.webp", 
    "asset/images/one_piece/Blenheim.webp", 
    "asset/images/one_piece/Bluegilly.webp", 
    "asset/images/one_piece/Blueno.webp", 
    "asset/images/one_piece/Boa Hancock.webp", 
    "asset/images/one_piece/Boa Marigold.webp", 
    "asset/images/one_piece/Boa Sandersonia.webp", 
    "asset/images/one_piece/Bobby Funk.webp", 
    "asset/images/one_piece/Bogard.webp", 
    "asset/images/one_piece/Bomba.webp", 
    "asset/images/one_piece/Bonk Punch.webp", 
    "asset/images/one_piece/Borsalino.webp", 
    "asset/images/one_piece/Bourbon Jr..webp", 
    "asset/images/one_piece/Brogy.webp", 
    "asset/images/one_piece/Brook.webp", 
    "asset/images/one_piece/Brutal Bull.webp", 
    "asset/images/one_piece/Buchi.webp", 
    "asset/images/one_piece/Buckingham Stussy.webp", 
    "asset/images/one_piece/Buffalo.webp", 
    "asset/images/one_piece/Buggy.webp", 
    "asset/images/one_piece/Building Snake.webp", 
    "asset/images/one_piece/Cabaji.webp", 
    "asset/images/one_piece/Caesar Clown.webp", 
    "asset/images/one_piece/Camie.webp", 
    "asset/images/one_piece/Capone Bege.webp", 
    "asset/images/one_piece/Capone Pez.webp", 
    "asset/images/one_piece/Capote.webp", 
    "asset/images/one_piece/Caribou.webp", 
    "asset/images/one_piece/Carmel.webp", 
    "asset/images/one_piece/Carrot.webp", 
    "asset/images/one_piece/Catarina Devon.webp", 
    "asset/images/one_piece/Cavendish.webp", 
    "asset/images/one_piece/Cerberus.webp", 
    "asset/images/one_piece/Charlos.webp", 
    "asset/images/one_piece/Charlotte Amande.webp", 
    "asset/images/one_piece/Charlotte Anana.webp", 
    "asset/images/one_piece/Charlotte Br�l�e.webp", 
    "asset/images/one_piece/Charlotte Chiffon.webp", 
    "asset/images/one_piece/Charlotte Cracker.webp", 
    "asset/images/one_piece/Charlotte Galette.webp", 
    "asset/images/one_piece/Charlotte Katakuri.webp", 
    "asset/images/one_piece/Charlotte Lola.webp", 
    "asset/images/one_piece/Charlotte Mont-d'Or.webp", 
    "asset/images/one_piece/Charlotte Moscato.webp", 
    "asset/images/one_piece/Charlotte Nusstorte.webp", 
    "asset/images/one_piece/Charlotte Opera.webp", 
    "asset/images/one_piece/Charlotte Perospero.webp", 
    "asset/images/one_piece/Charlotte Praline.webp", 
    "asset/images/one_piece/Charlotte Pudding.webp", 
    "asset/images/one_piece/Charlotte Smoothie.webp", 
    "asset/images/one_piece/Charlotte Snack.webp", 
    "asset/images/one_piece/Chess.webp", 
    "asset/images/one_piece/Chew.webp", 
    "asset/images/one_piece/Chimney.webp", 
    "asset/images/one_piece/Chinjao.webp", 
    "asset/images/one_piece/Choco Police.webp", 
    "asset/images/one_piece/Chocolat.webp", 
    "asset/images/one_piece/Chouchou.webp", 
    "asset/images/one_piece/Cla�omh D. Clover.webp", 
    "asset/images/one_piece/Cocoa.webp", 
    "asset/images/one_piece/Conis.webp", 
    "asset/images/one_piece/Coribou.webp", 
    "asset/images/one_piece/Cosette.webp", 
    "asset/images/one_piece/Cowboy.webp", 
    "asset/images/one_piece/Crocodile.webp", 
    "asset/images/one_piece/Crocus.webp", 
    "asset/images/one_piece/Curly Dadan.webp", 
    "asset/images/one_piece/Daifugo.webp", 
    "asset/images/one_piece/Dalmatian.webp", 
    "asset/images/one_piece/Dalton.webp", 
    "asset/images/one_piece/Daruma.webp", 
    "asset/images/one_piece/Daz Bonez.webp", 
    "asset/images/one_piece/Decalvan Brother.webp", 
    "asset/images/one_piece/Dellinger.webp", 
    "asset/images/one_piece/Demalo Black.webp", 
    "asset/images/one_piece/Denjiro.webp", 
    "asset/images/one_piece/Diamante.webp", 
    "asset/images/one_piece/Doberman.webp", 
    "asset/images/one_piece/Doc Q.webp", 
    "asset/images/one_piece/Doll.webp", 
    "asset/images/one_piece/Doma.webp", 
    "asset/images/one_piece/Domino.webp", 
    "asset/images/one_piece/Donquixote Doflamingo.webp", 
    "asset/images/one_piece/Donquixote Homing.webp", 
    "asset/images/one_piece/Donquixote Mjosgard.webp", 
    "asset/images/one_piece/Donquixote Rosinante.webp", 
    "asset/images/one_piece/Dorry.webp", 
    "asset/images/one_piece/Dracule Mihawk.webp", 
    "asset/images/one_piece/Drip.webp", 
    "asset/images/one_piece/Duval.webp", 
    "asset/images/one_piece/Edison.webp", 
    "asset/images/one_piece/Edward Newgate.webp", 
    "asset/images/one_piece/Edward Weevil.webp", 
    "asset/images/one_piece/Elizabello II.webp", 
    "asset/images/one_piece/Emet.webp", 
    "asset/images/one_piece/Emporio Ivankov.webp", 
    "asset/images/one_piece/Enel.webp", 
    "asset/images/one_piece/Ethanbaron V. Nusjuro.webp", 
    "asset/images/one_piece/Eustass Kid.webp", 
    "asset/images/one_piece/Fighting Bull.webp", 
    "asset/images/one_piece/Fisher Tiger.webp", 
    "asset/images/one_piece/Fossa.webp", 
    "asset/images/one_piece/Foxy.webp", 
    "asset/images/one_piece/Franky.webp", 
    "asset/images/one_piece/Fukaboshi.webp", 
    "asset/images/one_piece/Fukurokuju.webp", 
    "asset/images/one_piece/Fukurou.webp", 
    "asset/images/one_piece/Gaimon.webp", 
    "asset/images/one_piece/Galdino.webp", 
    "asset/images/one_piece/Gambia.webp", 
    "asset/images/one_piece/Gan Fall.webp", 
    "asset/images/one_piece/Gancho.webp", 
    "asset/images/one_piece/Gatz.webp", 
    "asset/images/one_piece/Gecko Moria.webp", 
    "asset/images/one_piece/Gedatsu.webp", 
    "asset/images/one_piece/Genbo.webp", 
    "asset/images/one_piece/Genzo.webp", 
    "asset/images/one_piece/Gin.webp", 
    "asset/images/one_piece/Ginrummy.webp", 
    "asset/images/one_piece/Gion.webp", 
    "asset/images/one_piece/Gismonda.webp", 
    "asset/images/one_piece/Gladius.webp", 
    "asset/images/one_piece/Gloriosa.webp", 
    "asset/images/one_piece/Going Merry.webp", 
    "asset/images/one_piece/Goki.webp", 
    "asset/images/one_piece/Gol D. Roger.webp", 
    "asset/images/one_piece/Gonbe.webp", 
    "asset/images/one_piece/Guernika.webp", 
    "asset/images/one_piece/Hack (Fishmen).webp", 
    "asset/images/one_piece/Hakugan.webp", 
    "asset/images/one_piece/Hamburg.webp", 
    "asset/images/one_piece/Hannyabal.webp", 
    "asset/images/one_piece/Haredas.webp", 
    "asset/images/one_piece/Hatchan.webp", 
    "asset/images/one_piece/Hattori.webp", 
    "asset/images/one_piece/Heat.webp", 
    "asset/images/one_piece/Helmeppo.webp", 
    "asset/images/one_piece/Hera.webp", 
    "asset/images/one_piece/Heracles.webp", 
    "asset/images/one_piece/Hibari.webp", 
    "asset/images/one_piece/Higuma.webp", 
    "asset/images/one_piece/Hikoichi.webp", 
    "asset/images/one_piece/Hiluluk.webp", 
    "asset/images/one_piece/Hina.webp", 
    "asset/images/one_piece/Hiramera.webp", 
    "asset/images/one_piece/Hogback.webp", 
    "asset/images/one_piece/Hongo.webp", 
    "asset/images/one_piece/Hyougoro.webp", 
    "asset/images/one_piece/Hyouzou.webp", 
    "asset/images/one_piece/Iceburg.webp", 
    "asset/images/one_piece/Igaram.webp", 
    "asset/images/one_piece/Ikkaku.webp", 
    "asset/images/one_piece/Imu.webp", 
    "asset/images/one_piece/Inazuma.webp", 
    "asset/images/one_piece/Inuarashi.webp", 
    "asset/images/one_piece/Ipponmatsu.webp", 
    "asset/images/one_piece/Issho.webp", 
    "asset/images/one_piece/Isuka.webp", 
    "asset/images/one_piece/Itomimizu.webp", 
    "asset/images/one_piece/Ivan X.webp", 
    "asset/images/one_piece/Izou.webp", 
    "asset/images/one_piece/Jabra.webp", 
    "asset/images/one_piece/Jack.webp", 
    "asset/images/one_piece/Jaguar D. Saul.webp", 
    "asset/images/one_piece/Jaki.webp", 
    "asset/images/one_piece/Jango.webp", 
    "asset/images/one_piece/Jaygarcia Saturn.webp", 
    "asset/images/one_piece/Jean Bart.webp", 
    "asset/images/one_piece/Jeet.webp", 
    "asset/images/one_piece/Jesus Burgess.webp", 
    "asset/images/one_piece/Jewelry Bonney.webp", 
    "asset/images/one_piece/Jimbei.webp", 
    "asset/images/one_piece/John Giant.webp", 
    "asset/images/one_piece/Johnny.webp", 
    "asset/images/one_piece/Joseph.webp", 
    "asset/images/one_piece/Joy Boy.webp", 
    "asset/images/one_piece/Jozu.webp", 
    "asset/images/one_piece/Kabu.webp", 
    "asset/images/one_piece/Kaidou.webp", 
    "asset/images/one_piece/Kaku.webp", 
    "asset/images/one_piece/Kalgara.webp", 
    "asset/images/one_piece/Kalifa.webp", 
    "asset/images/one_piece/Kamakiri.webp", 
    "asset/images/one_piece/Karoo.webp", 
    "asset/images/one_piece/Kashii.webp", 
    "asset/images/one_piece/Kawamatsu.webp", 
    "asset/images/one_piece/Kaya.webp", 
    "asset/images/one_piece/Kelly Funk.webp", 
    "asset/images/one_piece/Kentauros.webp", 
    "asset/images/one_piece/Kikunojo.webp", 
    "asset/images/one_piece/Kikyo.webp", 
    "asset/images/one_piece/Killer.webp", 
    "asset/images/one_piece/Kin'emon.webp", 
    "asset/images/one_piece/Kinderella.webp", 
    "asset/images/one_piece/King.webp", 
    "asset/images/one_piece/Kingbaum.webp", 
    "asset/images/one_piece/Kiwi.webp", 
    "asset/images/one_piece/Koby.webp", 
    "asset/images/one_piece/Kokoro.webp", 
    "asset/images/one_piece/Komachiyo.webp", 
    "asset/images/one_piece/Kong.webp", 
    "asset/images/one_piece/Kouzuki Hiyori.webp", 
    "asset/images/one_piece/Kouzuki Momonosuke.webp", 
    "asset/images/one_piece/Kouzuki Oden.webp", 
    "asset/images/one_piece/Kouzuki Sukiyaki.webp", 
    "asset/images/one_piece/Kouzuki Toki.webp", 
    "asset/images/one_piece/Krieg.webp", 
    "asset/images/one_piece/Kujaku.webp", 
    "asset/images/one_piece/Kumadori.webp", 
    "asset/images/one_piece/Kumashi.webp", 
    "asset/images/one_piece/Kureha.webp", 
    "asset/images/one_piece/Kuro.webp", 
    "asset/images/one_piece/Kuroobi.webp", 
    "asset/images/one_piece/Kurozumi Higurashi.webp", 
    "asset/images/one_piece/Kurozumi Kanjuro.webp", 
    "asset/images/one_piece/Kurozumi Orochi.webp", 
    "asset/images/one_piece/Kurozumi Semimaru.webp", 
    "asset/images/one_piece/Kurozumi Tama.webp", 
    "asset/images/one_piece/Kuzan.webp", 
    "asset/images/one_piece/Kyros.webp", 
    "asset/images/one_piece/Laboon.webp", 
    "asset/images/one_piece/Laffitte.webp", 
    "asset/images/one_piece/Lao G.webp", 
    "asset/images/one_piece/Leo.webp", 
    "asset/images/one_piece/Lilith.webp", 
    "asset/images/one_piece/Limejuice.webp", 
    "asset/images/one_piece/Lindbergh.webp", 
    "asset/images/one_piece/Lip Doughty.webp", 
    "asset/images/one_piece/Little Oars Jr..webp", 
    "asset/images/one_piece/Loki.webp", 
    "asset/images/one_piece/Lord of the Coast.webp", 
    "asset/images/one_piece/Lucky Roux.webp", 
    "asset/images/one_piece/Machvise.webp", 
    "asset/images/one_piece/Magellan.webp", 
    "asset/images/one_piece/Maha.webp", 
    "asset/images/one_piece/Makino.webp", 
    "asset/images/one_piece/Manjaro.webp", 
    "asset/images/one_piece/Mansherry.webp", 
    "asset/images/one_piece/Marco.webp", 
    "asset/images/one_piece/Marcus Mars.webp", 
    "asset/images/one_piece/Marguerite.webp", 
    "asset/images/one_piece/Marianne.webp", 
    "asset/images/one_piece/Marshall D. Teach.webp", 
    "asset/images/one_piece/Masked Deuce.webp", 
    "asset/images/one_piece/Merry.webp", 
    "asset/images/one_piece/Mikita.webp", 
    "asset/images/one_piece/Minokoala.webp", 
    "asset/images/one_piece/Minotaurus.webp", 
    "asset/images/one_piece/Misery.webp", 
    "asset/images/one_piece/Miss Father's Day.webp", 
    "asset/images/one_piece/Miss Friday.webp", 
    "asset/images/one_piece/Miss Monday.webp", 
    "asset/images/one_piece/Miyagi.webp", 
    "asset/images/one_piece/Mocha.webp", 
    "asset/images/one_piece/Mohji.webp", 
    "asset/images/one_piece/Momonga.webp", 
    "asset/images/one_piece/Momoo.webp", 
    "asset/images/one_piece/Monet.webp", 
    "asset/images/one_piece/Monkey D. Dragon.webp", 
    "asset/images/one_piece/Monkey D. Garp.webp", 
    "asset/images/one_piece/Monkey D. Luffy.webp", 
    "asset/images/one_piece/Mont Blanc Cricket.webp", 
    "asset/images/one_piece/Mont Blanc Noland.webp", 
    "asset/images/one_piece/Morgan.webp", 
    "asset/images/one_piece/Morgans.webp", 
    "asset/images/one_piece/Morley.webp", 
    "asset/images/one_piece/Mororon.webp", 
    "asset/images/one_piece/Mounblutain.webp", 
    "asset/images/one_piece/Mousse.webp", 
    "asset/images/one_piece/Mozu.webp", 
    "asset/images/one_piece/Mr. 13.webp", 
    "asset/images/one_piece/Mr. 5.webp", 
    "asset/images/one_piece/Mr. 7.webp", 
    "asset/images/one_piece/Nami.webp", 
    "asset/images/one_piece/Namur.webp", 
    "asset/images/one_piece/Napoleon.webp", 
    "asset/images/one_piece/Nefertari D. Cobra.webp", 
    "asset/images/one_piece/Nefertari D. Vivi.webp", 
    "asset/images/one_piece/Nefertari Titi.webp", 
    "asset/images/one_piece/Nekomamushi.webp", 
    "asset/images/one_piece/Neptune.webp", 
    "asset/images/one_piece/Nerine.webp", 
    "asset/images/one_piece/Nico Olvia.webp", 
    "asset/images/one_piece/Nico Robin.webp", 
    "asset/images/one_piece/Nika (God).webp", 
    "asset/images/one_piece/Nitro.webp", 
    "asset/images/one_piece/Noble Croc.webp", 
    "asset/images/one_piece/Nojiko.webp", 
    "asset/images/one_piece/Nola.webp", 
    "asset/images/one_piece/Nora Gitsune.webp", 
    "asset/images/one_piece/Nyasha.webp", 
    "asset/images/one_piece/Oars.webp", 
    "asset/images/one_piece/Omasa.webp", 
    "asset/images/one_piece/Onigumo.webp", 
    "asset/images/one_piece/Orlumbus.webp", 
    "asset/images/one_piece/Otohime.webp", 
    "asset/images/one_piece/Pagaya.webp", 
    "asset/images/one_piece/Page One.webp", 
    "asset/images/one_piece/Pandaman.webp", 
    "asset/images/one_piece/Pappag.webp", 
    "asset/images/one_piece/patty.webp", 
    "asset/images/one_piece/Paulie.webp", 
    "asset/images/one_piece/Pedro.webp", 
    "asset/images/one_piece/Pekoms.webp", 
    "asset/images/one_piece/Pell.webp", 
    "asset/images/one_piece/Penguin.webp", 
    "asset/images/one_piece/Perona.webp", 
    "asset/images/one_piece/Pica.webp", 
    "asset/images/one_piece/Pickles.webp", 
    "asset/images/one_piece/Porche.webp", 
    "asset/images/one_piece/Portgas D. Ace.webp", 
    "asset/images/one_piece/Portgas D. Rouge.webp", 
    "asset/images/one_piece/Pound.webp", 
    "asset/images/one_piece/Prince Grus.webp", 
    "asset/images/one_piece/Prometheus.webp", 
    "asset/images/one_piece/PX-5.webp", 
    "asset/images/one_piece/Pythagoras.webp", 
    "asset/images/one_piece/Queen Mama Chanter.webp", 
    "asset/images/one_piece/Queen.webp", 
    "asset/images/one_piece/Raijin.webp", 
    "asset/images/one_piece/Raizo.webp", 
    "asset/images/one_piece/Rakuyo.webp", 
    "asset/images/one_piece/Rebecca.webp", 
    "asset/images/one_piece/Rika.webp", 
    "asset/images/one_piece/Riku Doldo III.webp", 
    "asset/images/one_piece/Rob Lucci.webp", 
    "asset/images/one_piece/Roddy.webp", 
    "asset/images/one_piece/Roronoa Zoro.webp", 
    "asset/images/one_piece/Rosward.webp", 
    "asset/images/one_piece/Ryuboshi.webp", 
    "asset/images/one_piece/S-Bear.webp", 
    "asset/images/one_piece/S-Hawk.webp", 
    "asset/images/one_piece/S-Shark.webp", 
    "asset/images/one_piece/S-Snake.webp", 
    "asset/images/one_piece/Sabo.webp", 
    "asset/images/one_piece/Sadi.webp", 
    "asset/images/one_piece/Sai.webp", 
    "asset/images/one_piece/Sakazuki.webp", 
    "asset/images/one_piece/Salome.webp", 
    "asset/images/one_piece/Sanjuan Wolf.webp", 
    "asset/images/one_piece/Sarahebi.webp", 
    "asset/images/one_piece/Sarquiss.webp", 
    "asset/images/one_piece/Sasaki.webp", 
    "asset/images/one_piece/Scarlett.webp", 
    "asset/images/one_piece/Scopper Gaban.webp", 
    "asset/images/one_piece/Scratchmen Apoo.webp", 
    "asset/images/one_piece/Sengoku.webp", 
    "asset/images/one_piece/Senor Pink.webp", 
    "asset/images/one_piece/Sentomaru.webp", 
    "asset/images/one_piece/Shachi.webp", 
    "asset/images/one_piece/Shaka.webp", 
    "asset/images/one_piece/Shakuyaku.webp", 
    "asset/images/one_piece/Shalria.webp", 
    "asset/images/one_piece/Shanks.webp", 
    "asset/images/one_piece/Sharinguru.webp", 
    "asset/images/one_piece/Shepherd Ju Peter.webp", 
    "asset/images/one_piece/Shiki.webp", 
    "asset/images/one_piece/Shimotsuki Koushirou.webp", 
    "asset/images/one_piece/Shimotsuki Kuina.webp", 
    "asset/images/one_piece/Shimotsuki Ryuma.webp", 
    "asset/images/one_piece/Shimotsuki Yasuie.webp", 
    "asset/images/one_piece/Shinobu.webp", 
    "asset/images/one_piece/Shirahoshi.webp", 
    "asset/images/one_piece/Shirley.webp", 
    "asset/images/one_piece/Shiryu.webp", 
    "asset/images/one_piece/Shishilian.webp", 
    "asset/images/one_piece/Shu.webp", 
    "asset/images/one_piece/Shura.webp", 
    "asset/images/one_piece/Silvers Rayleigh.webp", 
    "asset/images/one_piece/Smiley.webp", 
    "asset/images/one_piece/Smoker.webp", 
    "asset/images/one_piece/Sodom and Gomorrah.webp", 
    "asset/images/one_piece/Spandam.webp", 
    "asset/images/one_piece/Speed.webp", 
    "asset/images/one_piece/Stansen.webp", 
    "asset/images/one_piece/Stomp.webp", 
    "asset/images/one_piece/Streusen.webp", 
    "asset/images/one_piece/Stussy.webp", 
    "asset/images/one_piece/Sugar.webp", 
    "asset/images/one_piece/Surume.webp", 
    "asset/images/one_piece/Sweet Pea.webp", 
    "asset/images/one_piece/T Bone.webp", 
    "asset/images/one_piece/Tamago.webp", 
    "asset/images/one_piece/Tashigi.webp", 
    "asset/images/one_piece/Terracotta.webp", 
    "asset/images/one_piece/Thatch.webp", 
    "asset/images/one_piece/Thousand Sunny.webp", 
    "asset/images/one_piece/Toko.webp", 
    "asset/images/one_piece/Tom.webp", 
    "asset/images/one_piece/Tony Tony Chopper.webp", 
    "asset/images/one_piece/Topman Warcury.webp", 
    "asset/images/one_piece/Trafalgar D Water Law.webp", 
    "asset/images/one_piece/Trafalgar D. Water Lami.webp", 
    "asset/images/one_piece/Trebol.webp", 
    "asset/images/one_piece/Tristan.webp", 
    "asset/images/one_piece/Tsunagoro.webp", 
    "asset/images/one_piece/Tsuru.webp", 
    "asset/images/one_piece/Tsurujo.webp", 
    "asset/images/one_piece/Turco.webp", 
    "asset/images/one_piece/Tyrannosaurus.webp", 
    "asset/images/one_piece/Ulti.webp", 
    "asset/images/one_piece/Urouge.webp", 
    "asset/images/one_piece/Usopp.webp", 
    "asset/images/one_piece/Uta.webp", 
    "asset/images/one_piece/Van Augur.webp", 
    "asset/images/one_piece/Vander Decken IX.webp", 
    "asset/images/one_piece/Vasco Shot.webp", 
    "asset/images/one_piece/Vegaforce-01.webp", 
    "asset/images/one_piece/Vergo.webp", 
    "asset/images/one_piece/Victoria Cindry.webp", 
    "asset/images/one_piece/Vinsmoke Ichiji.webp", 
    "asset/images/one_piece/Vinsmoke Judge.webp", 
    "asset/images/one_piece/Vinsmoke Niji.webp", 
    "asset/images/one_piece/Vinsmoke Reiju.webp", 
    "asset/images/one_piece/Vinsmoke Sanji.webp", 
    "asset/images/one_piece/Vinsmoke Sora.webp", 
    "asset/images/one_piece/Vinsmoke Yonji.webp", 
    "asset/images/one_piece/Viola.webp", 
    "asset/images/one_piece/Vista.webp", 
    "asset/images/one_piece/Vito.webp", 
    "asset/images/one_piece/Wadatsumi.webp", 
    "asset/images/one_piece/Wanda.webp", 
    "asset/images/one_piece/Wanze.webp", 
    "asset/images/one_piece/Wapol.webp", 
    "asset/images/one_piece/Who's-Who.webp", 
    "asset/images/one_piece/Wicca.webp", 
    "asset/images/one_piece/Wire.webp", 
    "asset/images/one_piece/Woop Slap.webp", 
    "asset/images/one_piece/Wyper.webp", 
    "asset/images/one_piece/X Drake.webp", 
    "asset/images/one_piece/Yamato.webp", 
    "asset/images/one_piece/yassopp.webp", 
    "asset/images/one_piece/Yokozuna.webp", 
    "asset/images/one_piece/York.webp", 
    "asset/images/one_piece/Yosaku.webp", 
    "asset/images/one_piece/Zeff.webp", 
    "asset/images/one_piece/Zeus.webp", 
    "asset/images/one_piece/Zunesha.webp", 
  ],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
  'Jujutsu Kaisen': [],
  'My Hero Academia': [],
  'Solo Leveling': [],
  'Tokyo Revengers': [],
  'Vinland Saga': [],
};
