const Map<String, List<String>> categoryAssets = {
  'Naruto': [],
  'Attack on Titan': [],
  'Hunter X Hunter': [],
  'Black Clover': [],
  'Bleach': [],
  'Code Geass': [],
  'Death Note': [],
  'Demon Slayer': [],
  'Detective Conan': [],
  'Dr. Stone': [],
  'Dragon Ball Z': [],
  'FMAB': [],
  'Jujutsu Kaisen': [],
  'My Hero Academia': [],
  'One Piece': [],
  'Solo Leveling': [],
  'Tokyo Revengers': [],
  'Vinland Saga': [],
};