// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgiFyEjRu0yuPaMtYPNndvi7FFXUozLgA',
    appId: '1:26367454001:web:4145b31a97c7dcd07c9e10',
    messagingSenderId: '26367454001',
    projectId: 'gdg-guess-game',
    authDomain: 'gdg-guess-game.firebaseapp.com',
    storageBucket: 'gdg-guess-game.firebasestorage.app',
    measurementId: 'G-ZFEJ64E7F0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARCTLL6Mqnm5-6AXcKq7KiamnV4aA52NU',
    appId: '1:26367454001:android:c5ab8b7e08f2604f7c9e10',
    messagingSenderId: '26367454001',
    projectId: 'gdg-guess-game',
    storageBucket: 'gdg-guess-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sGsN7u2GEtupS8OuZo6cq2fPWSbZJz8',
    appId: '1:26367454001:ios:c77cb489ad6498b57c9e10',
    messagingSenderId: '26367454001',
    projectId: 'gdg-guess-game',
    storageBucket: 'gdg-guess-game.firebasestorage.app',
    iosBundleId: 'com.example.gdgGuessGame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6sGsN7u2GEtupS8OuZo6cq2fPWSbZJz8',
    appId: '1:26367454001:ios:c77cb489ad6498b57c9e10',
    messagingSenderId: '26367454001',
    projectId: 'gdg-guess-game',
    storageBucket: 'gdg-guess-game.firebasestorage.app',
    iosBundleId: 'com.example.gdgGuessGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgiFyEjRu0yuPaMtYPNndvi7FFXUozLgA',
    appId: '1:26367454001:web:84a4e21e0af1d2ff7c9e10',
    messagingSenderId: '26367454001',
    projectId: 'gdg-guess-game',
    authDomain: 'gdg-guess-game.firebaseapp.com',
    storageBucket: 'gdg-guess-game.firebasestorage.app',
    measurementId: 'G-98Y5DCFG2S',
  );
}
