#!/usr/bin/env python3
"""
BiGuess Game - Asset Manifest Generator & Config Sync
Generates and synchronizes lib/assets_manifest.dart and pubspec.yaml
from the Topic/Pack hierarchy in assets/images/<Topic>/<Pack>/
"""

import argparse
import os
import re
import sys
import unicodedata
from pathlib import Path
from typing import Dict, List

# ANSI formatting
GREEN = "\033[92m"
YELLOW = "\033[93m"
RED = "\033[91m"
CYAN = "\033[96m"
BOLD = "\033[1m"
RESET = "\033[0m"

VALID_EXTENSIONS = {".webp", ".png", ".jpg", ".jpeg"}


def dart_quote(s: str) -> str:
    """Format string as a clean Dart string literal, avoiding unnecessary escaping."""
    if "'" in s and '"' not in s:
        return f'"{s}"'
    elif '"' in s and "'" not in s:
        return f"'{s}'"
    elif "'" in s and '"' in s:
        escaped = s.replace("'", "\\'")
        return f"'{escaped}'"
    else:
        return f"'{s}'"


def scan_topic_pack_assets(images_dir: Path) -> Dict[str, Dict[str, List[str]]]:
    """
    Scans images_dir and returns mapping of:
    { Topic: { Pack: [list of relative asset paths] } }
    """
    result: Dict[str, Dict[str, List[str]]] = {}

    if not images_dir.exists():
        print(f"{RED}❌ Directory not found: {images_dir}{RESET}")
        return result

    # Find all topic subdirectories
    topic_dirs = sorted([d for d in images_dir.iterdir() if d.is_dir() and not d.name.startswith(".")])

    for topic_dir in topic_dirs:
        topic_name = topic_dir.name
        pack_map: Dict[str, List[str]] = {}

        pack_dirs = sorted([p for p in topic_dir.iterdir() if p.is_dir() and not p.name.startswith(".")])
        for pack_dir in pack_dirs:
            pack_name = pack_dir.name
            asset_list: List[str] = []

            for item in pack_dir.iterdir():
                if item.is_file() and item.suffix.lower() in VALID_EXTENSIONS and not item.name.startswith("."):
                    normalized_name = unicodedata.normalize("NFC", item.name)
                    rel_path = f"assets/images/{topic_name}/{pack_name}/{normalized_name}"
                    asset_list.append(rel_path)

            asset_list.sort(key=lambda x: unicodedata.normalize("NFC", x.lower()))
            pack_map[pack_name] = asset_list

        if pack_map:
            result[topic_name] = pack_map

    return result


def generate_dart_content(manifest: Dict[str, Dict[str, List[str]]]) -> str:
    """Generate Dart code string for assets_manifest.dart."""
    lines = [
        "// GENERATED FILE - DO NOT EDIT MANUALLY",
        "// Generated by scripts/generate_manifest.py",
        "",
        "/// Topic -> Pack -> List of asset paths",
        "const Map<String, Map<String, List<String>>> topicPackAssets = {",
    ]

    for topic, packs in sorted(manifest.items()):
        lines.append(f"  {dart_quote(topic)}: {{")
        for pack, assets in sorted(packs.items()):
            lines.append(f"    {dart_quote(pack)}: [")
            for asset in assets:
                lines.append(f"      {dart_quote(asset)},")
            lines.append("    ],")
        lines.append("  },")

    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def sync_pubspec_assets(pubspec_path: Path, manifest: Dict[str, Dict[str, List[str]]]) -> bool:
    """Ensure all active Topic/Pack subfolders are accurately listed under assets: in pubspec.yaml."""
    if not pubspec_path.exists():
        print(f"{YELLOW}⚠️  pubspec.yaml not found at {pubspec_path}{RESET}")
        return False

    with open(pubspec_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Build the list of active pack directories
    expected_pack_entries = []
    for topic, packs in sorted(manifest.items()):
        expected_pack_entries.append(f"    # {topic} Topic")
        for pack in sorted(packs.keys()):
            expected_pack_entries.append(f"    - assets/images/{topic}/{pack}/")

    # Locate assets block in pubspec.yaml
    # We want to replace whatever is between `assets:` and `shorebird.yaml` (or `fonts:`)
    assets_match = re.search(r"(\s+assets:\s*\n)(.*?)(    - shorebird\.yaml)", content, re.DOTALL)
    if not assets_match:
        print(f"{RED}❌ Could not locate assets section in pubspec.yaml to sync.{RESET}")
        return False

    header = assets_match.group(1)
    footer = assets_match.group(3)

    # Standard static assets that must always be bundled
    base_assets = [
        "    - assets/logos/",
        "    - assets/profile/",
        "    - assets/fonts/",
    ]

    new_assets_block = "\n".join(base_assets + expected_pack_entries) + "\n"
    new_content = content[:assets_match.start(2)] + new_assets_block + content[assets_match.start(3):]

    if new_content == content:
        print(f"{GREEN}✅ pubspec.yaml assets section is already up to date.{RESET}")
        return True

    with open(pubspec_path, "w", encoding="utf-8") as f:
        f.write(new_content)

    print(f"{GREEN}✅ Updated pubspec.yaml with all active Topic/Pack directories.{RESET}")
    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate lib/assets_manifest.dart and sync assets from assets/images/.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    repo_root = Path(__file__).resolve().parent.parent
    default_images = repo_root / "assets" / "images"
    default_dart_out = repo_root / "lib" / "assets_manifest.dart"
    default_pubspec = repo_root / "pubspec.yaml"

    parser.add_argument(
        "-i", "--images-dir",
        type=Path,
        default=default_images,
        help="Path to assets/images folder",
    )
    parser.add_argument(
        "-o", "--output",
        type=Path,
        default=default_dart_out,
        help="Path to write assets_manifest.dart",
    )
    parser.add_argument(
        "--sync-pubspec",
        action="store_true",
        help="Automatically register all Topic/Pack folders in pubspec.yaml",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Check if manifest is up-to-date without modifying files (returns exit code 1 if diff exists)",
    )

    args = parser.parse_args()

    print(f"\n{BOLD}{CYAN}══════════════════════════════════════════════════════════════{RESET}")
    print(f"{BOLD}{CYAN}         📋  BiGuess Topic & Pack Manifest Generator           {RESET}")
    print(f"{BOLD}{CYAN}══════════════════════════════════════════════════════════════{RESET}")
    print(f"📁 Scanning:    {args.images_dir}")
    print(f"📄 Output:      {args.output}")
    print(f"{CYAN}──────────────────────────────────────────────────────────────{RESET}\n")

    manifest = scan_topic_pack_assets(args.images_dir)
    total_topics = len(manifest)
    total_packs = sum(len(packs) for packs in manifest.values())
    total_images = sum(
        sum(len(items) for items in packs.values())
        for packs in manifest.values()
    )

    for topic, packs in sorted(manifest.items()):
        topic_count = sum(len(items) for items in packs.values())
        print(f"  📂 {BOLD}{topic}{RESET} ({len(packs)} packs, {topic_count} items):")
        for pack, items in sorted(packs.items()):
            print(f"     • {pack:<25}: {len(items):>4} items")

    print(f"\n📊 Total: {BOLD}{total_topics}{RESET} topics, {BOLD}{total_packs}{RESET} packs, {BOLD}{total_images}{RESET} images.\n")

    new_dart_code = generate_dart_content(manifest)

    if args.check:
        if not args.output.exists():
            print(f"{RED}❌ Manifest file {args.output} does not exist.{RESET}")
            return 1
        with open(args.output, "r", encoding="utf-8") as f:
            existing_code = f.read()

        if existing_code.strip() == new_dart_code.strip():
            print(f"{GREEN}✅ Manifest is completely in sync with on-disk assets!{RESET}\n")
            return 0
        else:
            print(f"{RED}❌ Manifest is OUT OF SYNC with on-disk assets.{RESET}")
            print(f"Run {BOLD}python3 scripts/generate_manifest.py{RESET} to update it.\n")
            return 1

    # Write Dart manifest
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with open(args.output, "w", encoding="utf-8") as f:
        f.write(new_dart_code)
    print(f"{GREEN}✅ Successfully generated: {args.output}{RESET}")

    # Sync pubspec if requested
    if args.sync_pubspec:
        sync_pubspec_assets(default_pubspec, manifest)

    print(f"\n{BOLD}{CYAN}══════════════════════════════════════════════════════════════{RESET}\n")
    return 0


if __name__ == "__main__":
    sys.exit(main())
